import type { PlaybookFile } from '../types';

export const creative: PlaybookFile = {
  id: 'creative',
  title: 'Creative release',
  deck: 'A song, a poster, a video, a drop. Luck waits until you hit publish.',
  situationPrompt: 'What are you putting out?',
  situationPlaceholder: 'Suno single Friday, poster for cinema night, video cut…',
  questions: [
    {
      id: 'what',
      prompt: 'What is it?',
      options: [
        { id: 'song', label: 'Song / audio' },
        { id: 'image', label: 'Poster / still' },
        { id: 'video', label: 'Video' },
        { id: 'drop', label: 'A drop / pack / store' },
      ],
    },
    {
      id: 'date',
      prompt: 'Is there a public date?',
      options: [
        { id: 'tonight', label: 'Tonight / tomorrow' },
        { id: 'locked', label: 'Locked on a calendar' },
        { id: 'soft', label: 'Soft / whenever it’s ready' },
      ],
    },
    {
      id: 'people',
      prompt: 'Other humans in the file?',
      options: [
        { id: 'solo', label: 'Just me' },
        { id: 'collab', label: 'A collaborator' },
        { id: 'client', label: 'A client / a brand' },
      ],
    },
    {
      id: 'where',
      prompt: 'Where does it go first?',
      multiple: true,
      options: [
        { id: 'ig', label: 'Instagram' },
        { id: 'yt', label: 'YouTube / TikTok' },
        { id: 'dsp', label: 'Spotify / DSPs' },
        { id: 'print', label: 'Print / physical' },
        { id: 'email', label: 'Email / a list' },
      ],
    },
    {
      id: 'money',
      prompt: 'Money on the line?',
      options: [
        { id: 'none', label: 'No' },
        { id: 'ads', label: 'Ads / boost' },
        { id: 'sale', label: 'People will pay' },
      ],
    },
    {
      id: 'master',
      prompt: 'Where is the master file right now?',
      options: [
        { id: 'one', label: 'One laptop / one drive' },
        { id: 'cloud', label: 'Cloud, I think' },
        { id: 'several', label: 'Several places on purpose' },
      ],
    },
  ],
  hazards: [
    {
      id: 'wrong-file',
      name: 'You publish the almost-final',
      blurb: 'v7-final-REAL, the one with the old title, the export with the watermark. Luck files by date, you file by hope.',
      counter: 'One folder called SHIP. Only the file in that folder goes out. A 60-second listen/look after export, not before.',
      kind: 'cursed',
      base: 24,
      bump: [
        { question: 'date', option: 'tonight', by: 22 },
        { question: 'what', option: 'song', by: 8 },
        { question: 'what', option: 'video', by: 10 },
      ],
    },
    {
      id: 'credit',
      name: 'A name is wrong, missing, or spelled like a dare',
      blurb: 'Luck waits for the screenshot. Collaborators remember forever. Clients remember in email.',
      counter: 'A written credit line approved in the thread, copied into the caption before the asset. No memory.',
      job: 'Whoever hits post',
      kind: 'annoying',
      base: 12,
      bump: [
        { question: 'people', option: 'collab', by: 36 },
        { question: 'people', option: 'client', by: 40 },
        { question: 'where', option: 'ig', by: 8 },
      ],
    },
    {
      id: 'rights',
      name: 'A face, a font, a sample, or a logo you do not actually have',
      blurb: 'Luck is the person who recognizes their work at 2am.',
      counter: 'If you cannot point to permission, it does not ship. Especially client work. Especially print.',
      kind: 'cursed',
      base: 14,
      bump: [
        { question: 'people', option: 'client', by: 22 },
        { question: 'where', option: 'print', by: 24 },
        { question: 'money', option: 'sale', by: 16 },
        { question: 'what', option: 'song', by: 10 },
      ],
    },
    {
      id: 'one-drive',
      name: 'The only copy lives on the machine that will choose tomorrow',
      blurb: 'Luck does not need ransomware. It needs a coffee and an open bag.',
      counter: 'Two places that are not the same laptop. Export + project. Do it before you celebrate.',
      kind: 'cursed',
      base: 10,
      bump: [
        { question: 'master', option: 'one', by: 55 },
        { question: 'master', option: 'cloud', by: 12 },
        { question: 'date', option: 'tonight', by: 8 },
      ],
    },
    {
      id: 'caption',
      name: 'The caption is where the night actually dies',
      blurb: 'Wrong date, wrong link, a tag that notifies an ex, a link in bio that still goes to the last thing.',
      counter: 'Write the caption first in notes. Links tested in an incognito window. Then attach the art.',
      kind: 'likely',
      base: 28,
      bump: [
        { question: 'where', option: 'ig', by: 16 },
        { question: 'where', option: 'email', by: 10 },
        { question: 'date', option: 'tonight', by: 10 },
      ],
    },
    {
      id: 'dsp',
      name: 'The store / DSP needs a week you already spent',
      blurb: 'Spotify, print shops, app stores. Luck invented “processing.”',
      counter: 'If the date is public, the file should already be in the machine that distributes it. Not tonight.',
      kind: 'annoying',
      base: 8,
      bump: [
        { question: 'where', option: 'dsp', by: 40 },
        { question: 'where', option: 'print', by: 28 },
        { question: 'date', option: 'tonight', by: 16 },
        { question: 'date', option: 'locked', by: 12 },
      ],
    },
    {
      id: 'client-notes',
      name: 'The client has one more note and it is about the whole thing',
      blurb: 'Luck speaks fluent “quick tweak.” It arrives after you posted the teaser.',
      counter: 'A lock email: after this time, we ship what’s approved. Tease only locked frames.',
      job: 'You, with a spine',
      kind: 'annoying',
      base: 8,
      bump: [
        { question: 'people', option: 'client', by: 48 },
        { question: 'date', option: 'locked', by: 12 },
        { question: 'date', option: 'tonight', by: 10 },
      ],
    },
    {
      id: 'ratio',
      name: 'The crop murders the thing',
      blurb: 'A square that beheads the title. A story-safe zone you ignored. Print bleed you guessed.',
      counter: 'Export the actual placements, not “we’ll crop later.” Read the title at thumbnail size.',
      kind: 'likely',
      base: 18,
      bump: [
        { question: 'what', option: 'image', by: 28 },
        { question: 'what', option: 'video', by: 16 },
        { question: 'where', option: 'ig', by: 12 },
        { question: 'where', option: 'print', by: 18 },
      ],
    },
    {
      id: 'silence',
      name: 'It goes out and the room is quiet and you panic-edit',
      blurb: 'Luck is not the algorithm. Luck is you rewriting a finished thing at 12:40 because nobody liked it yet.',
      counter: 'A 24-hour rule. You may pin, you may reply, you may not silently replace the file.',
      kind: 'likely',
      base: 22,
      bump: [
        { question: 'people', option: 'solo', by: 12 },
        { question: 'date', option: 'tonight', by: 10 },
        { question: 'money', option: 'ads', by: 8 },
      ],
    },
    {
      id: 'ads',
      name: 'The boost starts before the link is the right link',
      blurb: 'Paid luck is just expensive confusion. Wrong URL, old event, a pixel on the draft page.',
      counter: 'Click the ad destination yourself. Then spend.',
      kind: 'cursed',
      base: 6,
      bump: [
        { question: 'money', option: 'ads', by: 52 },
        { question: 'money', option: 'sale', by: 16 },
      ],
    },
  ],
};
