import type { PlaybookFile } from '../types';

export const dateSocial: PlaybookFile = {
  id: 'date-social',
  title: 'Date / social',
  deck: 'Two or more humans, a plan that sounded easy in daylight. Luck sits in the third chair.',
  situationPrompt: 'What is the plan?',
  situationPlaceholder: 'First drink at 7, or a family dinner you cannot ghost…',
  questions: [
    {
      id: 'kind',
      prompt: 'What kind of night?',
      options: [
        { id: 'first', label: 'First date / new person' },
        { id: 'two', label: 'Us, already a thing' },
        { id: 'group', label: 'Group' },
        { id: 'family', label: 'Family / obligated' },
      ],
    },
    {
      id: 'where',
      prompt: 'Where?',
      options: [
        { id: 'bar', label: 'Bar / restaurant' },
        { id: 'home', label: 'Someone’s home' },
        { id: 'out', label: 'A thing with tickets' },
        { id: 'walk', label: 'Walk / outside / vague' },
      ],
    },
    {
      id: 'booked',
      prompt: 'Is there a reservation or a ticket?',
      options: [
        { id: 'yes', label: 'Yes, named and timed' },
        { id: 'hope', label: 'We’ll walk in' },
        { id: 'no', label: 'No need' },
      ],
    },
    {
      id: 'who-pays',
      prompt: 'Money awkwardness?',
      options: [
        { id: 'fine', label: 'Handled' },
        { id: 'unclear', label: 'Unclear' },
        { id: 'them', label: 'I’m hoping they get it' },
      ],
    },
    {
      id: 'exit',
      prompt: 'Do you have an exit?',
      options: [
        { id: 'yes', label: 'A real one' },
        { id: 'maybe', label: '“We’ll see”' },
        { id: 'stuck', label: 'I am stuck if it sours' },
      ],
    },
    {
      id: 'when',
      prompt: 'How soon?',
      options: [
        { id: 'now', label: 'Tonight / tomorrow' },
        { id: 'week', label: 'This week' },
        { id: 'later', label: 'Later' },
      ],
    },
  ],
  hazards: [
    {
      id: 'place-dead',
      name: 'The place is slammed, closed, or a different place now',
      blurb: 'Luck reads Google hours better than you. Walk-ins on a Saturday are a hobby, not a plan.',
      counter: 'A named backup within two blocks. Confirm hours the day of. If it matters, book it.',
      kind: 'likely',
      base: 16,
      bump: [
        { question: 'booked', option: 'hope', by: 40 },
        { question: 'where', option: 'bar', by: 14 },
        { question: 'when', option: 'now', by: 10 },
        { question: 'kind', option: 'first', by: 8 },
      ],
    },
    {
      id: 'late',
      name: 'Someone is late and nobody says the true time',
      blurb: 'Luck is twenty minutes of you looking at the door rehearsing your face.',
      counter: 'A check-in text with a clock. After 15 minutes, the backup plan (leave, order, go home) already exists.',
      kind: 'likely',
      base: 26,
      bump: [
        { question: 'kind', option: 'group', by: 16 },
        { question: 'kind', option: 'first', by: 10 },
        { question: 'booked', option: 'yes', by: 12 },
      ],
    },
    {
      id: 'check',
      name: 'The check arrives and the night gets smaller',
      blurb: 'Luck is bad at splitting. It is worse at “no no let me.”',
      counter: 'Decide before you sit down. If it’s a first date, pick a place where the bill cannot become the plot.',
      kind: 'annoying',
      base: 10,
      bump: [
        { question: 'who-pays', option: 'unclear', by: 40 },
        { question: 'who-pays', option: 'them', by: 28 },
        { question: 'kind', option: 'first', by: 12 },
        { question: 'kind', option: 'group', by: 16 },
      ],
    },
    {
      id: 'no-exit',
      name: 'You cannot leave without a scene',
      blurb: 'Their car, a remote restaurant, a family table, a ticket in the middle of a row. Luck designs traps that look like plans.',
      counter: 'Your own way home. An outside time. A friend who will text at 9:40 if you want them to.',
      kind: 'cursed',
      base: 8,
      bump: [
        { question: 'exit', option: 'stuck', by: 55 },
        { question: 'exit', option: 'maybe', by: 22 },
        { question: 'kind', option: 'first', by: 12 },
        { question: 'kind', option: 'family', by: 10 },
      ],
    },
    {
      id: 'phone',
      name: 'The phone becomes a third person',
      blurb: 'Work, an ex, a group chat exploding. Luck loves a banner notification at the worst sentence.',
      counter: 'Do not disturb. If you might get pulled, say so up front instead of performing surprise.',
      kind: 'likely',
      base: 20,
      bump: [
        { question: 'kind', option: 'first', by: 10 },
        { question: 'kind', option: 'two', by: 8 },
        { question: 'when', option: 'now', by: 6 },
      ],
    },
    {
      id: 'home-mess',
      name: 'If it goes to a home, the home is a witness',
      blurb: 'Roommate, dishes, a bathroom you did not inspect, a pet with opinions. Luck lives in the medicine cabinet.',
      counter: 'A ten-minute pass: bathroom, lights, a surface to put a glass. A roommate warning.',
      kind: 'annoying',
      base: 8,
      bump: [
        { question: 'where', option: 'home', by: 48 },
        { question: 'kind', option: 'first', by: 10 },
      ],
    },
    {
      id: 'tickets',
      name: 'The tickets are in the other inbox',
      blurb: 'Luck forwards nothing. Doors are unimpressed by “it’s on my phone somewhere.”',
      counter: 'Screenshots, wallet passes, a meeting spot outside that is not “by the thing.”',
      kind: 'annoying',
      base: 8,
      bump: [
        { question: 'where', option: 'out', by: 48 },
        { question: 'booked', option: 'yes', by: 12 },
        { question: 'kind', option: 'group', by: 8 },
      ],
    },
    {
      id: 'family',
      name: 'A relative will pick a topic that is a land mine',
      blurb: 'Luck knows your map. Work, bodies, money, the person who is not there.',
      counter: 'A partner signal. Two safe topics. You are allowed to get water for a long time.',
      kind: 'likely',
      base: 6,
      bump: [
        { question: 'kind', option: 'family', by: 60 },
        { question: 'exit', option: 'stuck', by: 10 },
      ],
    },
    {
      id: 'weather-date',
      name: 'The vague outdoor plan meets actual weather',
      blurb: 'Walks are not reservations. Luck owns the temperature after 8.',
      counter: 'A roof. A time you bail. Shoes that can do more than the photo.',
      kind: 'annoying',
      base: 8,
      bump: [
        { question: 'where', option: 'walk', by: 50 },
        { question: 'booked', option: 'no', by: 8 },
        { question: 'when', option: 'now', by: 8 },
      ],
    },
    {
      id: 'group-plan',
      name: 'The group chat will plan a second night on top of this one',
      blurb: 'Luck adds a bar, a person, a “quick stop.” Your original plan dies of kindness.',
      counter: 'A stated end. If you want the night to stay small, say the smallness out loud.',
      kind: 'likely',
      base: 10,
      bump: [
        { question: 'kind', option: 'group', by: 44 },
        { question: 'kind', option: 'two', by: 8 },
        { question: 'exit', option: 'maybe', by: 10 },
      ],
    },
  ],
};
