import type { PlaybookFile } from '../types';

export const launch: PlaybookFile = {
  id: 'launch',
  title: 'Launch',
  deck: 'A form, a site, a product, an announcement. Luck clicks the link first, as a stranger.',
  situationPrompt: 'What is going live?',
  situationPlaceholder: 'New lead form, a drop, an announcement, a paid thing…',
  questions: [
    {
      id: 'what',
      prompt: 'What kind of launch?',
      options: [
        { id: 'site', label: 'Site / page' },
        { id: 'form', label: 'Form / signup' },
        { id: 'product', label: 'Thing people pay for' },
        { id: 'news', label: 'Announcement only' },
      ],
    },
    {
      id: 'audience',
      prompt: 'Who sees it first?',
      options: [
        { id: 'friends', label: 'Friends / a small list' },
        { id: 'public', label: 'Public' },
        { id: 'paid', label: 'Paid traffic' },
      ],
    },
    {
      id: 'when',
      prompt: 'When?',
      options: [
        { id: 'now', label: 'Now-ish' },
        { id: 'dated', label: 'A date people already have' },
        { id: 'soft', label: 'Soft launch' },
      ],
    },
    {
      id: 'who',
      prompt: 'Who can fix it after it breaks?',
      options: [
        { id: 'me', label: 'Only me' },
        { id: 'two', label: 'Me + one other' },
        { id: 'team', label: 'A real team' },
      ],
    },
    {
      id: 'data',
      prompt: 'Does it take money or personal data?',
      options: [
        { id: 'no', label: 'No' },
        { id: 'email', label: 'Emails / info' },
        { id: 'money', label: 'Money' },
      ],
    },
    {
      id: 'tested',
      prompt: 'Have you used it as a stranger?',
      options: [
        { id: 'yes', label: 'Yes, on a phone, logged out' },
        { id: 'kind', label: 'I clicked around while logged in' },
        { id: 'no', label: 'Not really' },
      ],
    },
  ],
  hazards: [
    {
      id: 'link',
      name: 'The link in the post is the wrong link',
      blurb: 'Old event, staging, a typo, a linktree still pointing at December. Luck is the first click you did not make.',
      counter: 'Open the exact URL from the exact post in a private window on a phone. Then tell people.',
      kind: 'cursed',
      base: 20,
      bump: [
        { question: 'tested', option: 'no', by: 28 },
        { question: 'tested', option: 'kind', by: 16 },
        { question: 'audience', option: 'paid', by: 16 },
        { question: 'when', option: 'now', by: 8 },
      ],
    },
    {
      id: 'mobile',
      name: 'It only works on your laptop',
      blurb: 'Luck has thumbs. Forms that hide the button, type that collides, a checkout that cannot take Apple Pay because you never looked.',
      counter: 'One pass on a real phone. If a field is annoying to you, it is a wall to everyone else.',
      kind: 'likely',
      base: 24,
      bump: [
        { question: 'what', option: 'form', by: 16 },
        { question: 'what', option: 'product', by: 14 },
        { question: 'tested', option: 'no', by: 20 },
        { question: 'tested', option: 'kind', by: 12 },
      ],
    },
    {
      id: 'noreply',
      name: 'The confirmation email goes to spam or to nowhere',
      blurb: 'Luck signs up as a civilian. You signed up as the owner and got the nice path.',
      counter: 'Submit once with a personal email you do not control. Check junk. If money is involved, do a $1 test.',
      kind: 'annoying',
      base: 14,
      bump: [
        { question: 'data', option: 'email', by: 28 },
        { question: 'data', option: 'money', by: 32 },
        { question: 'what', option: 'form', by: 12 },
        { question: 'what', option: 'product', by: 12 },
      ],
    },
    {
      id: 'solo',
      name: 'It breaks at dinner and you are the only one with keys',
      blurb: 'Luck does not respect time zones or dates. It respects single points of failure.',
      counter: 'A second admin. A written “if this dies” note. Do not launch only-you on a night you will be at a table.',
      kind: 'cursed',
      base: 10,
      bump: [
        { question: 'who', option: 'me', by: 42 },
        { question: 'when', option: 'dated', by: 12 },
        { question: 'audience', option: 'public', by: 8 },
        { question: 'audience', option: 'paid', by: 10 },
      ],
    },
    {
      id: 'copy',
      name: 'The words still say draft',
      blurb: 'Lorem, a leftover price, “TBD,” the old date. Luck screenshots.',
      counter: 'Search the page for TBD, lorem, 2025, your name spelled wrong, the last event’s title.',
      kind: 'likely',
      base: 22,
      bump: [
        { question: 'when', option: 'now', by: 14 },
        { question: 'tested', option: 'no', by: 12 },
        { question: 'what', option: 'news', by: 8 },
      ],
    },
    {
      id: 'traffic',
      name: 'The one thing that cannot scale is the thing you paid to advertise',
      blurb: 'A form that emails you personally. A calendar that double-books. Luck buys the ads.',
      counter: 'Know the failure mode at 10×. If it is your inbox, it is not a launch, it is a dare.',
      kind: 'annoying',
      base: 8,
      bump: [
        { question: 'audience', option: 'paid', by: 40 },
        { question: 'audience', option: 'public', by: 16 },
        { question: 'what', option: 'form', by: 10 },
        { question: 'data', option: 'money', by: 12 },
      ],
    },
    {
      id: 'legal',
      name: 'You asked for money or data without the boring sentences',
      blurb: 'Refunds, spam rules, a price that was a joke. Luck forwards the page to someone with a lawyer.',
      counter: 'A real price, a real refund line, a way to opt out. Especially if a client’s name is on it.',
      kind: 'cursed',
      base: 8,
      bump: [
        { question: 'data', option: 'money', by: 36 },
        { question: 'data', option: 'email', by: 16 },
        { question: 'what', option: 'product', by: 12 },
      ],
    },
    {
      id: 'og',
      name: 'The share card is still the default nothing',
      blurb: 'Luck is the preview in iMessage: a blank page, the wrong title, a random image from 2022.',
      counter: 'Paste the URL into a preview debugger. Then post.',
      kind: 'annoying',
      base: 18,
      bump: [
        { question: 'what', option: 'news', by: 16 },
        { question: 'what', option: 'site', by: 12 },
        { question: 'audience', option: 'public', by: 10 },
      ],
    },
    {
      id: 'timezone',
      name: 'The date is true in your kitchen and false everywhere else',
      blurb: 'Luck lives in other time zones. “Friday” is not a time.',
      counter: 'Put a timezone on the thing. If it is a door time, say the city.',
      kind: 'likely',
      base: 16,
      bump: [
        { question: 'when', option: 'dated', by: 22 },
        { question: 'what', option: 'news', by: 10 },
        { question: 'audience', option: 'public', by: 8 },
      ],
    },
    {
      id: 'analytics',
      name: 'You will not know if it worked because nothing is measuring',
      blurb: 'Luck is a successful launch you cannot prove, so you “tweak” a working page.',
      counter: 'One number you will look at tomorrow. That is enough. Do not launch blind and then rewrite.',
      kind: 'likely',
      base: 20,
      bump: [
        { question: 'tested', option: 'no', by: 10 },
        { question: 'audience', option: 'paid', by: 14 },
        { question: 'who', option: 'me', by: 8 },
      ],
    },
  ],
};
