import type { PlaybookFile } from '../types';

export const liveEvent: PlaybookFile = {
  id: 'live-event',
  title: 'Live event',
  deck: 'A night with a door, a clock, and other people. Luck loves a run of show.',
  situationPrompt: 'What is the night?',
  situationPlaceholder: 'Cube rental Saturday, 120 guests, DJ, plated dinner…',
  questions: [
    {
      id: 'where',
      prompt: 'Where does it happen?',
      options: [
        { id: 'indoor', label: 'Indoor' },
        { id: 'outdoor', label: 'Outdoor' },
        { id: 'mixed', label: 'Indoor + outdoor' },
      ],
    },
    {
      id: 'size',
      prompt: 'How many bodies, honestly?',
      options: [
        { id: 'tiny', label: 'Under 25' },
        { id: 'house', label: '25–80' },
        { id: 'room', label: '80–200' },
        { id: 'crush', label: '200+' },
      ],
    },
    {
      id: 'food',
      prompt: 'Food?',
      options: [
        { id: 'none', label: 'None / snacks' },
        { id: 'drop', label: 'Dropped off' },
        { id: 'cater', label: 'Full catering' },
        { id: 'diy', label: 'We are the kitchen' },
      ],
    },
    {
      id: 'sound',
      prompt: 'Sound in the room?',
      multiple: true,
      options: [
        { id: 'playlist', label: 'Playlist' },
        { id: 'dj', label: 'DJ' },
        { id: 'band', label: 'Live band' },
        { id: 'speech', label: 'Mics / speeches' },
        { id: 'none', label: 'None of that' },
      ],
    },
    {
      id: 'money',
      prompt: 'Who is paying for this to work?',
      options: [
        { id: 'host', label: 'I am hosting' },
        { id: 'tickets', label: 'Tickets / door' },
        { id: 'client', label: 'A client is paying' },
      ],
    },
    {
      id: 'when',
      prompt: 'How soon?',
      options: [
        { id: 'now', label: 'In 48 hours' },
        { id: 'week', label: 'This week' },
        { id: 'later', label: 'Later' },
      ],
    },
    {
      id: 'booze',
      prompt: 'Alcohol?',
      options: [
        { id: 'yes', label: 'Yes' },
        { id: 'no', label: 'No' },
      ],
    },
    {
      id: 'hook',
      prompt: 'If it breaks, who has to explain it?',
      options: [
        { id: 'me', label: 'Me' },
        { id: 'client', label: 'A client' },
        { id: 'committee', label: 'A committee' },
      ],
    },
  ],
  hazards: [
    {
      id: 'headcount',
      name: 'The headcount you have is not the headcount that arrives',
      blurb: 'Plus-ones, no-shows, and “I told Maya.” Luck edits the list at the door.',
      counter: 'A hard cap in writing. One person owns the list. Food is ordered to the cap, not the dream.',
      job: 'List owner',
      kind: 'likely',
      base: 28,
      bump: [
        { question: 'size', option: 'room', by: 18 },
        { question: 'size', option: 'crush', by: 28 },
        { question: 'money', option: 'tickets', by: 12 },
        { question: 'hook', option: 'committee', by: 10 },
      ],
    },
    {
      id: 'weather',
      name: 'The sky does not care about your Pinterest',
      blurb: 'Outdoor nights fail in the most ordinary way: water, wind, or a sun that cooks the cheese.',
      counter: 'A real indoor backup, not a tent you might rent. Decide the trigger now (time + forecast), not at 4pm.',
      job: 'Producer',
      kind: 'cursed',
      base: 8,
      bump: [
        { question: 'where', option: 'outdoor', by: 70 },
        { question: 'where', option: 'mixed', by: 42 },
        { question: 'when', option: 'now', by: 10 },
      ],
    },
    {
      id: 'power',
      name: 'The circuit that runs the night is the one someone plugged a heater into',
      blurb: 'DJ, catering wells, string lights, the coffee urn. Luck finds the shared outlet.',
      counter: 'Walk the power. Label circuits. Band/DJ on their own, kitchen on theirs. A spare fuse is not a personality.',
      job: 'Venue / band tech',
      kind: 'cursed',
      base: 16,
      bump: [
        { question: 'sound', option: 'dj', by: 18 },
        { question: 'sound', option: 'band', by: 22 },
        { question: 'food', option: 'cater', by: 14 },
        { question: 'food', option: 'diy', by: 12 },
        { question: 'size', option: 'crush', by: 10 },
      ],
    },
    {
      id: 'talent',
      name: 'The DJ / band is on a different clock than the speeches',
      blurb: 'They were told “around eight.” Speeches start at 8:40. Luck lives in “around.”',
      counter: 'One printed run-of-show in their hand, with clock times, not vibes. A cell number that actually answers.',
      job: 'Whoever booked the sound',
      kind: 'annoying',
      base: 14,
      bump: [
        { question: 'sound', option: 'dj', by: 32 },
        { question: 'sound', option: 'band', by: 34 },
        { question: 'sound', option: 'speech', by: 16 },
        { question: 'when', option: 'now', by: 8 },
      ],
    },
    {
      id: 'catering',
      name: 'Food is late and the room is already drunk or starving',
      blurb: 'Dropped-off trays in a hot car. A plated service that misses the speech. Luck eats first.',
      counter: 'A buffer course (nuts, bread, something) that does not depend on the truck. Confirm arrival window in writing.',
      job: 'Kitchen lead',
      kind: 'annoying',
      base: 10,
      bump: [
        { question: 'food', option: 'drop', by: 36 },
        { question: 'food', option: 'cater', by: 28 },
        { question: 'food', option: 'diy', by: 30 },
        { question: 'booze', option: 'yes', by: 12 },
        { question: 'when', option: 'now', by: 8 },
      ],
    },
    {
      id: 'adapter',
      name: 'Nobody brought the adapter',
      blurb: 'HDMI, 3.5mm, USB-C, the dongle that makes the playlist leave a phone. Luck collects these.',
      counter: 'A labeled pouch: HDMI, aux, USB-C, extension, power strip. It lives in the same bag every time.',
      job: 'AV / host',
      kind: 'likely',
      base: 22,
      bump: [
        { question: 'sound', option: 'playlist', by: 28 },
        { question: 'sound', option: 'speech', by: 18 },
        { question: 'sound', option: 'dj', by: 8 },
      ],
    },
    {
      id: 'alcohol',
      name: 'The open bar outruns the food and the speeches',
      blurb: 'Luck does not cut anyone off. It just hands the mic to the wrong uncle.',
      counter: 'Food before pour, a closer who can close, water on every table, one person allowed to say no.',
      job: 'Bar + host',
      kind: 'annoying',
      base: 6,
      bump: [
        { question: 'booze', option: 'yes', by: 48 },
        { question: 'food', option: 'none', by: 16 },
        { question: 'sound', option: 'speech', by: 10 },
        { question: 'size', option: 'crush', by: 8 },
      ],
    },
    {
      id: 'parking',
      name: 'Parking becomes the first activity of the night',
      blurb: 'Guests start twenty minutes angry. Vendors cannot load. Luck invented the last two blocks.',
      counter: 'A map, a load-in window, an overflow lot, a text that goes out the morning of — not in the invite footer.',
      job: 'Host',
      kind: 'likely',
      base: 20,
      bump: [
        { question: 'size', option: 'room', by: 16 },
        { question: 'size', option: 'crush', by: 28 },
        { question: 'where', option: 'outdoor', by: 8 },
        { question: 'money', option: 'tickets', by: 8 },
      ],
    },
    {
      id: 'timeline',
      name: 'Everything slips twenty minutes and nobody calls it',
      blurb: 'Doors late, speeches late, cake late, vendor overtime. Luck is just unannounced drift.',
      counter: 'A written clock. One person is allowed to cut a toast. Vendors know the real end time, not the hopeful one.',
      job: 'Stage manager (even if that is you)',
      kind: 'likely',
      base: 30,
      bump: [
        { question: 'sound', option: 'speech', by: 16 },
        { question: 'when', option: 'now', by: 12 },
        { question: 'hook', option: 'committee', by: 14 },
        { question: 'size', option: 'room', by: 8 },
      ],
    },
    {
      id: 'client',
      name: 'The person paying wants a new night at 6:12pm',
      blurb: 'Headcount, color, a cousin who “has to speak.” Luck arrives as a friendly text.',
      counter: 'A freeze time. After that, the answer is “we can do that next time.” Put it in the confirmation.',
      job: 'Whoever owns the client',
      kind: 'annoying',
      base: 8,
      bump: [
        { question: 'money', option: 'client', by: 40 },
        { question: 'hook', option: 'client', by: 22 },
        { question: 'hook', option: 'committee', by: 18 },
        { question: 'when', option: 'now', by: 10 },
      ],
    },
    {
      id: 'door',
      name: 'The door is chaos and the night never recovers',
      blurb: 'List, cash, wristbands, “I’m on the list.” Luck starts arguments where the first impression is.',
      counter: 'Two people at the door, a paper backup of the list, a script for no. Cash in a box, not a pocket.',
      job: 'Door',
      kind: 'annoying',
      base: 12,
      bump: [
        { question: 'money', option: 'tickets', by: 36 },
        { question: 'size', option: 'room', by: 14 },
        { question: 'size', option: 'crush', by: 22 },
      ],
    },
    {
      id: 'neighbor',
      name: 'A neighbor or a cop becomes your closer',
      blurb: 'Outdoor sound, indoor bass, a 10pm room in a 9pm neighborhood. Luck has a doorbell.',
      counter: 'Know the real curfew. A volume plan. A host who goes outside and talks like an adult before anyone else does.',
      job: 'Host',
      kind: 'cursed',
      base: 10,
      bump: [
        { question: 'where', option: 'outdoor', by: 28 },
        { question: 'where', option: 'mixed', by: 16 },
        { question: 'sound', option: 'band', by: 18 },
        { question: 'sound', option: 'dj', by: 12 },
        { question: 'booze', option: 'yes', by: 8 },
      ],
    },
    {
      id: 'loadout',
      name: 'Load-out is when things walk away',
      blurb: 'Cables, a guest’s coat, the tip jar, a case left by the door. Luck works the last twenty minutes.',
      counter: 'A close checklist. Two people until the last car. Gear staged in one pile, not “we’ll grab it.”',
      job: 'Last adult standing',
      kind: 'likely',
      base: 18,
      bump: [
        { question: 'sound', option: 'band', by: 16 },
        { question: 'sound', option: 'dj', by: 12 },
        { question: 'size', option: 'crush', by: 10 },
        { question: 'when', option: 'now', by: 6 },
      ],
    },
    {
      id: 'bathroom',
      name: 'The bathroom line becomes the afterparty',
      blurb: 'One stall, a broken lock, no paper. Luck is not glamorous.',
      counter: 'Check paper, soap, a sign for the second restroom, a plunger you are not ashamed of.',
      job: 'Venue',
      kind: 'likely',
      base: 16,
      bump: [
        { question: 'size', option: 'house', by: 10 },
        { question: 'size', option: 'room', by: 18 },
        { question: 'size', option: 'crush', by: 28 },
        { question: 'booze', option: 'yes', by: 10 },
      ],
    },
  ],
};
