import type { PlaybookFile } from '../types';

export const shoot: PlaybookFile = {
  id: 'shoot',
  title: 'Shoot',
  deck: 'A camera, a clock, and a location that looked fine on a recce you skipped. Luck owns the weather and the card.',
  situationPrompt: 'What are you shooting?',
  situationPlaceholder: 'Band in a room, talking-head, outdoor stills, a whole day with talent…',
  questions: [
    {
      id: 'where',
      prompt: 'Where?',
      options: [
        { id: 'studio', label: 'Controlled room' },
        { id: 'inside', label: 'A real indoor place' },
        { id: 'outside', label: 'Outside' },
        { id: 'run', label: 'Run-and-gun / several places' },
      ],
    },
    {
      id: 'who',
      prompt: 'Who has to show up?',
      options: [
        { id: 'me', label: 'Just me' },
        { id: 'talent', label: 'Talent / a face' },
        { id: 'crew', label: 'A crew' },
      ],
    },
    {
      id: 'when',
      prompt: 'How soon, and can it move?',
      options: [
        { id: 'fixed', label: 'The day cannot move' },
        { id: 'soon', label: 'Soon, some flex' },
        { id: 'soft', label: 'Soft' },
      ],
    },
    {
      id: 'sound',
      prompt: 'Do you need clean sound?',
      options: [
        { id: 'yes', label: 'Yes, it matters' },
        { id: 'some', label: 'A little' },
        { id: 'no', label: 'Picture only' },
      ],
    },
    {
      id: 'permit',
      prompt: 'Permission to be there?',
      options: [
        { id: 'ours', label: 'It’s ours / we have it' },
        { id: 'maybe', label: 'We’ll be fine' },
        { id: 'public', label: 'Public / gray' },
      ],
    },
    {
      id: 'cards',
      prompt: 'Media and power plan?',
      options: [
        { id: 'real', label: 'Spare cards, spare batteries, a dump plan' },
        { id: 'enough', label: 'Should be enough' },
        { id: 'thin', label: 'We are thin' },
      ],
    },
  ],
  hazards: [
    {
      id: 'card',
      name: 'The card fills, corrupts, or is the one you did not format',
      blurb: 'Luck eats the take you loved. It prefers the last 20 minutes.',
      counter: 'Format in camera. Dual slot if you have it. Dump before you wrap. Never shoot the only copy on the only card.',
      kind: 'cursed',
      base: 12,
      bump: [
        { question: 'cards', option: 'thin', by: 50 },
        { question: 'cards', option: 'enough', by: 22 },
        { question: 'when', option: 'fixed', by: 10 },
      ],
    },
    {
      id: 'battery',
      name: 'Power dies on the line you cannot get again',
      blurb: 'Luck waits for the good take. Cameras, mics, lights, a phone used as a monitor.',
      counter: 'Charged spares in a pouch, not in a bag at home. Someone owns power the way someone owns the shot list.',
      kind: 'annoying',
      base: 16,
      bump: [
        { question: 'cards', option: 'thin', by: 28 },
        { question: 'who', option: 'talent', by: 10 },
        { question: 'where', option: 'run', by: 12 },
        { question: 'where', option: 'outside', by: 8 },
      ],
    },
    {
      id: 'weather-shoot',
      name: 'The light you recce’d is not the light you get',
      blurb: 'Clouds, wind in the lav, a sun that moves into a wall. Luck is a gaffer with a sense of humor.',
      counter: 'A cover set. A time you call it. Don’t schedule the only shot of the day for “golden hour maybe.”',
      kind: 'cursed',
      base: 8,
      bump: [
        { question: 'where', option: 'outside', by: 52 },
        { question: 'where', option: 'run', by: 24 },
        { question: 'when', option: 'fixed', by: 16 },
      ],
    },
    {
      id: 'sound-shoot',
      name: 'The room is pretty and unusable',
      blurb: 'HVAC, a fridge, a street, a refrigerator truck that arrives for the neighbor. Luck is an unlogged hum.',
      counter: 'Headphones on the first minute, not the last. A quiet room as backup. Lav plus a backup recorder.',
      kind: 'annoying',
      base: 10,
      bump: [
        { question: 'sound', option: 'yes', by: 48 },
        { question: 'sound', option: 'some', by: 20 },
        { question: 'where', option: 'inside', by: 10 },
        { question: 'where', option: 'outside', by: 12 },
      ],
    },
    {
      id: 'talent',
      name: 'The face is late, shiny, or in a shirt that dies on camera',
      blurb: 'Luck books wardrobe from a pile. It also books traffic.',
      counter: 'A call time with a pad. A backup top. Water, powder, a shot list they can survive if energy drops.',
      job: 'Whoever called the talent',
      kind: 'likely',
      base: 12,
      bump: [
        { question: 'who', option: 'talent', by: 40 },
        { question: 'who', option: 'crew', by: 16 },
        { question: 'when', option: 'fixed', by: 10 },
      ],
    },
    {
      id: 'permit',
      name: 'Someone with a vest asks what you think you are doing',
      blurb: 'Luck wears a lanyard. Public is not permission. “We’ll be fast” is not a permit.',
      counter: 'If it is the only location, get it in writing. Have a second place that does not need a vest.',
      kind: 'cursed',
      base: 8,
      bump: [
        { question: 'permit', option: 'public', by: 48 },
        { question: 'permit', option: 'maybe', by: 36 },
        { question: 'who', option: 'crew', by: 10 },
        { question: 'where', option: 'outside', by: 8 },
      ],
    },
    {
      id: 'shotlist',
      name: 'You will shoot the fun thing and miss the thing you came for',
      blurb: 'Luck is a beautiful B-roll addiction. Editors cannot invent the line you did not record.',
      counter: 'Must-haves first, in writing, on paper. Fun after. Wrap when the list is done, not when you are inspired.',
      kind: 'likely',
      base: 24,
      bump: [
        { question: 'when', option: 'fixed', by: 12 },
        { question: 'who', option: 'me', by: 8 },
        { question: 'where', option: 'run', by: 10 },
      ],
    },
    {
      id: 'dump',
      name: 'You wrap and the files stay on the camera overnight “because we’re tired”',
      blurb: 'Luck loves a camera in a trunk. It loves a card on a bar.',
      counter: 'Dump before anyone drinks. Check playback of the must-haves. Then you can be tired.',
      kind: 'cursed',
      base: 16,
      bump: [
        { question: 'cards', option: 'thin', by: 16 },
        { question: 'cards', option: 'enough', by: 10 },
        { question: 'when', option: 'fixed', by: 8 },
      ],
    },
    {
      id: 'crew',
      name: 'Too many people, not enough jobs',
      blurb: 'Luck is a friend with a camera who is also “helping with sound.” Nobody owns the card.',
      counter: 'Three jobs on paper: picture, sound, clock. If a person does not have a job, they are a guest.',
      kind: 'annoying',
      base: 8,
      bump: [
        { question: 'who', option: 'crew', by: 40 },
        { question: 'who', option: 'talent', by: 8 },
      ],
    },
    {
      id: 'golden',
      name: 'You planned the whole day around a twenty-minute sky',
      blurb: 'Luck knows golden hour is a rumor with a union. It is also earlier than you think.',
      counter: 'Be set before the light. The day cannot be “and then sunset.” Sunset is a bonus, not a plot.',
      kind: 'annoying',
      base: 10,
      bump: [
        { question: 'where', option: 'outside', by: 32 },
        { question: 'when', option: 'fixed', by: 12 },
        { question: 'where', option: 'run', by: 10 },
      ],
    },
  ],
};
