import type { PlaybookFile } from '../types';

export const travel: PlaybookFile = {
  id: 'travel',
  title: 'Travel',
  deck: 'A clock, a vehicle, and a version of you that packed at 1am. Luck loves a connection.',
  situationPrompt: 'Where are you going, and why does it matter?',
  situationPlaceholder: 'DEN → LGA Friday, tight connection, cannot miss the thing…',
  questions: [
    {
      id: 'mode',
      prompt: 'How are you moving?',
      options: [
        { id: 'fly', label: 'Fly' },
        { id: 'drive', label: 'Drive' },
        { id: 'train', label: 'Train / bus' },
        { id: 'mix', label: 'More than one of those' },
      ],
    },
    {
      id: 'stakes',
      prompt: 'If you are late, what breaks?',
      options: [
        { id: 'vacation', label: 'Vacation mood' },
        { id: 'work', label: 'Work / a meeting' },
        { id: 'event', label: 'A thing I cannot miss' },
        { id: 'home', label: 'Getting home' },
      ],
    },
    {
      id: 'connect',
      prompt: 'Layover or tight timing?',
      options: [
        { id: 'none', label: 'Straight through' },
        { id: 'easy', label: 'A comfortable pad' },
        { id: 'tight', label: 'Under an hour / cutting it' },
        { id: 'unknown', label: 'I have not looked' },
      ],
    },
    {
      id: 'who',
      prompt: 'Who is coming?',
      options: [
        { id: 'solo', label: 'Just me' },
        { id: 'two', label: 'Two of us' },
        { id: 'pack', label: 'A group / kids' },
      ],
    },
    {
      id: 'bags',
      prompt: 'Bags?',
      options: [
        { id: 'carry', label: 'Carry-on only' },
        { id: 'check', label: 'Checked bag' },
        { id: 'gear', label: 'Gear / instruments / a lot' },
      ],
    },
    {
      id: 'border',
      prompt: 'Borders, IDs, the boring stuff?',
      options: [
        { id: 'domestic', label: 'Domestic, I think I’m fine' },
        { id: 'id', label: 'ID / REAL ID is a maybe' },
        { id: 'intl', label: 'International' },
      ],
    },
    {
      id: 'when',
      prompt: 'How soon?',
      options: [
        { id: 'now', label: 'In 48 hours' },
        { id: 'week', label: 'This week' },
        { id: 'later', label: 'Later' },
      ],
    },
  ],
  hazards: [
    {
      id: 'connection',
      name: 'The connection is the whole trip and it is a fantasy',
      blurb: 'Luck does not sprint with you to C17. It waits at the first delay and cashes the rest.',
      counter: 'If missing it ruins the thing, you need a pad or a later backup already booked. “We’ll make it” is not a plan.',
      job: 'You',
      kind: 'cursed',
      base: 10,
      bump: [
        { question: 'connect', option: 'tight', by: 62 },
        { question: 'connect', option: 'unknown', by: 40 },
        { question: 'mode', option: 'fly', by: 12 },
        { question: 'mode', option: 'mix', by: 16 },
        { question: 'stakes', option: 'event', by: 16 },
      ],
    },
    {
      id: 'id',
      name: 'The document that gets you on is the one in the other pants',
      blurb: 'REAL ID, passport expiration, a license that is a photo on your phone. Luck checks bags at your doorway.',
      counter: 'Physical ID in the same pocket every trip, photographed, plus a backup. Check expiration tonight, not at TSA.',
      kind: 'cursed',
      base: 14,
      bump: [
        { question: 'border', option: 'id', by: 50 },
        { question: 'border', option: 'intl', by: 36 },
        { question: 'when', option: 'now', by: 12 },
      ],
    },
    {
      id: 'bag',
      name: 'The checked bag goes to a city you are not in',
      blurb: 'Luck loves a 40-minute connection and a suitcase with your shoes for the thing.',
      counter: 'Wear/carry what the trip cannot survive without. Apple tag. A photo of the bag. One day of clothes on your back.',
      kind: 'annoying',
      base: 8,
      bump: [
        { question: 'bags', option: 'check', by: 36 },
        { question: 'bags', option: 'gear', by: 44 },
        { question: 'connect', option: 'tight', by: 16 },
        { question: 'mode', option: 'fly', by: 10 },
      ],
    },
    {
      id: 'car',
      name: 'The car dies in the least cinematic way',
      blurb: 'Tire, battery, empty tank, a warning light you have been ignoring. Luck does not need a cliff.',
      counter: 'Fuel, spare, cables, a real tire check. Screenshot roadside assistance before you lose signal.',
      kind: 'annoying',
      base: 8,
      bump: [
        { question: 'mode', option: 'drive', by: 48 },
        { question: 'mode', option: 'mix', by: 20 },
        { question: 'who', option: 'pack', by: 10 },
        { question: 'when', option: 'now', by: 8 },
      ],
    },
    {
      id: 'group',
      name: 'The group cannot occupy one timeline',
      blurb: 'Someone is always in a bathroom, a gift shop, or “two minutes.” Luck multiplies by headcount.',
      counter: 'A meeting point, a leave time that is not negotiable, one person who is allowed to be rude about clocks.',
      job: 'The mean one',
      kind: 'likely',
      base: 12,
      bump: [
        { question: 'who', option: 'pack', by: 48 },
        { question: 'who', option: 'two', by: 16 },
        { question: 'connect', option: 'tight', by: 12 },
      ],
    },
    {
      id: 'weather-fly',
      name: 'Weather cancels the first leg and you have no second story',
      blurb: 'Luck reads the radar so you do not have to, then it reads your itinerary.',
      counter: 'Alerts on. Know the last backup that still makes the thing. Travel insurance is not a personality but it is a tool.',
      kind: 'cursed',
      base: 14,
      bump: [
        { question: 'mode', option: 'fly', by: 18 },
        { question: 'stakes', option: 'event', by: 22 },
        { question: 'connect', option: 'tight', by: 12 },
        { question: 'when', option: 'now', by: 8 },
      ],
    },
    {
      id: 'phone',
      name: 'Your phone is the ticket, the map, and the boarding pass, and it dies',
      blurb: 'Luck invented 3% battery at the scanner.',
      counter: 'Screenshot every pass. A battery pack that actually holds charge. Paper backup for the one flight that matters.',
      kind: 'likely',
      base: 26,
      bump: [
        { question: 'mode', option: 'fly', by: 12 },
        { question: 'mode', option: 'mix', by: 10 },
        { question: 'when', option: 'now', by: 6 },
      ],
    },
    {
      id: 'home',
      name: 'The house you left is the problem, not the trip',
      blurb: 'Unlocked door, a pet, a bill, a plant, a parking ticket growing in the driveway. Luck stays home too.',
      counter: 'A 90-second leave checklist on paper: locks, stove, pet, trash, charger, ID.',
      kind: 'likely',
      base: 20,
      bump: [
        { question: 'when', option: 'now', by: 12 },
        { question: 'who', option: 'solo', by: 8 },
      ],
    },
    {
      id: 'work-call',
      name: 'The meeting starts while you are still in a tunnel',
      blurb: 'Luck schedules the important call for taxi, security, or the one stretch with no signal.',
      counter: 'A buffer. A note that you might be late. A deck that someone else can open. Do not be the only person with the file.',
      kind: 'annoying',
      base: 8,
      bump: [
        { question: 'stakes', option: 'work', by: 44 },
        { question: 'stakes', option: 'event', by: 12 },
        { question: 'connect', option: 'tight', by: 10 },
      ],
    },
    {
      id: 'intl',
      name: 'The border is slower than your story about yourself',
      blurb: 'Visa, ETA, a stamp, a form you were supposed to do on the plane. Luck reads the fine print.',
      counter: 'Official site, tonight. Screenshots of approval. Hours at the other end that are not your hours.',
      kind: 'cursed',
      base: 6,
      bump: [
        { question: 'border', option: 'intl', by: 58 },
        { question: 'when', option: 'now', by: 12 },
      ],
    },
    {
      id: 'gear',
      name: 'The thing you are traveling to use gets handled like a suitcase',
      blurb: 'Instruments, cameras, a dress that cannot be folded. Luck works for baggage throwers.',
      counter: 'Carry it on or don’t bring it. Hard case. A local rental as the real backup, not optimism.',
      kind: 'cursed',
      base: 6,
      bump: [
        { question: 'bags', option: 'gear', by: 55 },
        { question: 'mode', option: 'fly', by: 10 },
      ],
    },
  ],
};
