export const HOUSE_DECK = [
  "Drink a full glass of water",
  "Write someone a short thank-you note",
  "Paint a small rock",
  "Read one full chapter of a book",
  "Take a ten-minute walk",
  "Give someone a sincere compliment",
  "Make your bed",
  "Stretch your whole body for five minutes",
  "Watch a sunset from beginning to end",
  "Write down three things you appreciate today",
  "Call someone you have not spoken with recently",
  "Pick up ten pieces of litter",
  "Draw a self-portrait without worrying about accuracy",
  "Learn one new word and use it in a sentence",
  "Send someone a song you think they would enjoy",
  "Completely organize one drawer",
  "Sit outside for ten minutes without looking at your phone",
  "Write a four-line poem",
  "Eat one piece of fresh fruit",
  "Do twenty comfortable bodyweight squats",
  "Photograph something ordinary that looks beautiful in the right light",
  "Leave someone a short encouraging note",
  "Delete twenty useless photos from your phone",
  "Clear everything unnecessary off your nightstand",
  "Listen to one album from beginning to end without shuffling it",
  "Write down one realistic goal for the next thirty days",
  "Try one food you have never tasted before",
  "Spend five minutes watching clouds move",
  "Learn how to say \"thank you\" in a language you do not speak",
  "Clean your phone screen thoroughly",
  "Write and mail or hand-deliver a postcard",
  "Hold a wall sit until you want to stop, then stay five more seconds if comfortable",
  "Put away ten things that are currently out of place",
  "Make a paper airplane and see how far it flies",
  "Read one article about a subject you know almost nothing about",
  "Tell someone one specific thing you appreciate about them",
  "Take ten slow breaths while paying attention to each one",
  "Fill one sheet of paper with doodles",
  "Water a plant that needs it",
  "Write down one memory you never want to forget",
  "Spend five minutes looking at the night sky",
  "Make yourself your favorite sandwich",
  "Learn one simple magic trick and perform it for someone",
  "Unsubscribe from five email lists you never read",
  "Give away one useful item you no longer need",
  "Walk somewhere nearby that you would normally drive to",
  "Write a note for yourself to read one year from today",
  "Do ten push-ups or a comfortable modified version",
  "Listen to a song released in the year you were born",
  "Clean one mirror until it is streak-free",
  "Make a handmade bookmark",
  "Find one object in your home that you forgot you owned",
  "Send someone a message telling them you are glad you know them",
  "Spend ten minutes doing something with no productive purpose",
  "Learn how to identify one constellation",
  "Make yourself a warm drink and enjoy it without multitasking",
  "Walk a familiar route in the opposite direction",
  "Write down five things you are genuinely good at",
  "Remove every unnecessary item from your wallet or purse",
  "Put clean sheets on your bed",
  "Draw something without lifting your pen from the paper",
  "Learn one interesting fact about the place where you live",
  "Say one kind thing about yourself out loud",
  "Watch a bird until it flies away or leaves your view",
  "Complete one small task you have been avoiding",
  "Write a complete story using exactly six words",
  "Eat one snack slowly without looking at a screen",
  "Completely organize one shelf",
  "Photograph something that makes you laugh",
  "Listen to three songs from a music genre you rarely choose",
  "Write down the best thing that happened to you this week",
  "Stand barefoot on safe grass for a few minutes",
  "Invent a ridiculous superhero identity for yourself",
  "Thoroughly wash your reusable water bottle",
  "Learn how to fold one piece of simple origami",
  "Leave a positive review for a business you genuinely appreciate",
  "Read ten pages of nonfiction",
  "Write down one worry you are willing to stop feeding today",
  "Do thirty jumping jacks or another comfortable one-minute exercise",
  "Create something using only scrap paper",
  "Send someone an old photo that includes both of you",
  "Clean your computer keyboard",
  "Wake up early enough to watch a sunrise",
  "Memorize one short quotation you love",
  "Keep your phone out of reach for thirty uninterrupted minutes",
  "Invent a one-paragraph fictional biography for a stranger you notice",
  "Learn the capital city of a country you have never visited",
  "Put one unused possession into a donation box",
  "Hum your favorite song from beginning to end",
  "Make yourself a snack you loved as a child",
  "Write your full name three times using your nondominant hand",
  "Spend five minutes stretching your neck and shoulders",
  "Photograph an interesting shadow",
  "Walk down one nearby street you have never explored on foot",
  "Write down ten things that reliably make you laugh",
  "Clean one window",
  "Tell someone about a favorite memory you have with them",
  "Learn one useful phrase in sign language",
  "Sit somewhere you normally walk past for five minutes",
  "Make one person laugh today",
  "Read one poem you have never read before",
  "Completely organize your junk drawer",
  "Find the oldest object you personally own and learn what you can about it",
  "Photograph an object that has sentimental value and write one sentence about why",
  "Write the story behind one object you have kept for years",
  "Make a five-song playlist designed to improve your mood",
  "Clean one pair of shoes",
  "Hold a plank for a comfortable amount of time and record your result",
  "Write a haiku about where you are right now",
  "Draw an object while keeping your eyes closed",
  "Ask someone how their day is going and listen without interrupting",
  "Eat one vegetable you have not eaten recently",
  "Clean underneath or behind one piece of furniture",
  "Collect and recycle five recyclable items that are lying around",
  "Learn the name of one tree that grows near you",
  "Sit still for three minutes and identify as many different sounds as you can",
  "Write down your earliest clear childhood memory",
  "Send someone a picture or joke you know they will find funny",
  "Rearrange one small area of your room to make it work better",
  "Learn one keyboard shortcut that will save you time",
  "Walk continuously for the length of three songs",
  "Fold a paper boat",
  "Read the first five pages of a book you have never opened",
  "Give one person your complete attention for an entire conversation",
  "Wash your pillowcase",
  "Take a photograph in which blue is the dominant color",
  "Write about one opinion you have changed during your life",
  "Learn one tongue twister and say it correctly three times",
  "Spend five minutes doing gentle mobility exercises",
  "Find an old coin and learn one fact about the year printed on it",
  "Write a short letter to your younger self",
  "Completely clean one kitchen cabinet",
  "Choose five possessions you would be comfortable giving away",
  "Look through old photographs for ten minutes",
  "Try to whistle an entire simple song",
  "Learn to recognize the flag of a country you could not identify before",
  "Make a snack using only ingredients you already have",
  "Sit in complete silence for five minutes",
  "Summarize your entire day in one sentence",
  "Take a photograph from ground level",
  "Read something printed on paper for fifteen minutes",
  "Tell someone specifically what they did well today",
  "Write down ten places you would like to visit someday",
  "Dust one surface you usually forget about",
  "Look up the current phase of the moon and then find it in the sky if visible",
  "Draw a map of your neighborhood from memory",
  "Write down five smells you enjoy",
  "Find and photograph something naturally symmetrical",
  "Hold a door open for someone",
  "Return one misplaced object to the place where it actually belongs",
  "Write a funny limerick",
  "Learn three facts about an animal you like",
  "Set a five-minute timer and clean as much of one room as possible",
  "Make breakfast food for dinner",
  "Take three photographs using reflections as the main subject",
  "Spend ten minutes without saying a word",
  "Learn how to tie one knot you did not know before",
  "Write down one question you would love to know the answer to",
  "Ask someone about one of their favorite childhood memories",
  "Find something naturally shaped like a heart",
  "Read the full ingredient list on something you eat regularly",
  "Organize one folder on your computer",
  "Delete five apps you no longer use",
  "Change one old or weak password to a strong unique password",
  "Wash your hands slowly enough to do it thoroughly",
  "Draw your ideal home without worrying about realism",
  "Find and listen to a song you loved ten years ago",
  "Send someone a song that reminds you of a time you shared",
  "Write three sentences describing your day so far",
  "Make a drink you have never prepared for yourself before",
  "Sit on a public bench for five minutes and simply observe your surroundings",
  "Count how many different colors you can see from one spot",
  "Learn one fact about the building you are currently in",
  "Do twenty slow calf raises",
  "Write down one thing you are genuinely looking forward to",
  "Clean three frequently touched doorknobs or handles",
  "Take one photograph without using digital zoom",
  "Build a tiny sculpture from ordinary household objects",
  "Read one complete encyclopedia or Wikipedia article about a random subject",
  "Guess which way is north without your phone, then check",
  "Recommend one book, movie, song, or restaurant you love",
  "Invent a new word and write down its definition",
  "Brush your teeth carefully for a full two minutes",
  "Write down five people who have taught you something valuable",
  "Thank one person who taught you something valuable",
  "Take a five-minute walk with no planned destination",
  "Find something nearby that is older than you are",
  "Hide a positive note somewhere you will unexpectedly find it later",
  "Learn how to make one simple origami animal",
  "Clean the top of a refrigerator, cabinet, or other high surface",
  "Spend five minutes closely looking at one piece of art",
  "Draw your favorite animal entirely from memory",
  "Style your hair differently than usual",
  "Make one room smell fresher using something you already have",
  "Find the brightest star or planet visible in the night sky",
  "Eat one entire meal without looking at your phone",
  "Write yourself a ridiculous fortune-cookie fortune",
  "Invent a handshake with someone",
  "Learn one fact about the nearest river, lake, creek, or ocean",
  "Do one kind thing anonymously",
  "Write down ten things you can see from where you are sitting",
  "Close your eyes and identify five different sounds",
  "Spend one minute noticing temperature, texture, and pressure",
  "Take the funniest deliberately bad selfie you can manage",
  "Take a self-portrait you genuinely like without using a beauty filter",
  "Make a custom phone wallpaper from one of your own photographs",
  "Clean your glasses or sunglasses thoroughly",
  "Learn to recognize the sound of one local bird",
  "Identify one flower growing near you",
  "Write a four-line song about something that happened today",
  "Sing a song you know from beginning to end",
  "Read one page of a book aloud",
  "Balance on each foot for thirty seconds",
  "Wash one dish immediately after using it",
  "Untangle and organize all the cables in one small area",
  "Rename ten confusing computer files so their contents are obvious",
  "Clear unnecessary files out of your downloads folder",
  "Delete ten old screenshots you no longer need",
  "Back up one digital file you would hate to lose",
  "Find one photograph that instantly improves your mood",
  "Print, frame, or display a photograph you love",
  "Write down the funniest thing you remember happening at school",
  "Look up the definition of a word you have heard but never fully understood",
  "Build something useful or ridiculous using paper and tape",
  "Draw your hand from observation without tracing it",
  "Trace your hand and transform the outline into an animal or character",
  "Write a mystery story in one paragraph",
  "Complete a crossword, word search, Sudoku, or other small puzzle",
  "Learn the rules of one simple card game",
  "Practice shuffling cards for five minutes",
  "Build the tallest freestanding tower you can from nearby safe objects",
  "Set a three-minute timer and clean one small space as efficiently as possible",
  "Eat something crunchy and pay attention to the texture",
  "Eat one naturally green food",
  "Drink a glass of water before your next cup of coffee or soda",
  "Fill a glass with ice water and finish the entire glass",
  "Lay out tomorrow's clothes before going to bed",
  "Go to bed twenty minutes earlier than your usual bedtime",
  "Keep your phone untouched for the first ten minutes after waking up",
  "Open a window for five minutes if the weather and air quality are suitable",
  "Guess the outdoor temperature before checking it",
  "Guess what time it is before looking at a clock",
  "Guess how many steps it takes to cross one room, then count the actual number",
  "Measure the length of an object using only your hand as the measuring tool",
  "Make a grocery list entirely from memory before checking your kitchen",
  "Check your kitchen for ingredients you already own before buying duplicates",
  "Use up one ingredient that has been sitting in your pantry for a while",
  "Make one meal primarily from leftovers",
  "Learn how to cook one simple dish without following instructions",
  "Prepare one meal slowly enough to enjoy making it",
  "Make an unnecessarily fancy piece of toast",
  "Cut an ordinary sandwich into an unusual shape",
  "Eat one food you loved when you were a child",
  "Ask someone what their ultimate comfort food is",
  "Share one easy recipe you genuinely recommend",
  "Thoroughly clean one small kitchen appliance",
  "Wipe the inside of your microwave",
  "Organize your spice cabinet or spice shelf",
  "Close your eyes, smell three spices, and try to identify them",
  "Flavor a glass of water with fruit or herbs you already have",
  "Freeze pieces of fruit for a future snack",
  "Make popcorn from kernels if you have them",
  "Eat one meal outdoors",
  "Have a picnic on the floor inside your home",
  "Eat dinner using only candles or soft lighting if it is safe to do so",
  "Use your nicest cup, plate, or bowl for an ordinary meal",
  "Arrange a basic snack as if it came from a fancy restaurant",
  "Write down the exact components of your ideal meal",
  "Ask someone you know for a recipe they love",
  "Learn how one common food item is manufactured or grown",
  "Eat one meal or snack using chopsticks",
  "Make a small dessert from ingredients you already have",
  "Wash and prepare fruit or vegetables so they are ready to eat later",
  "Completely clean one refrigerator shelf",
  "Check five food items for expiration or best-by dates",
  "Move older food to the front so you are more likely to use it",
  "Plan one meal that uses ingredients you would otherwise waste",
  "Save appropriate vegetable scraps to make stock",
  "Try growing a plant from a seed or food scrap",
  "Plant one seed in soil and keep track of whether it sprouts",
  "Give one of your plants a name",
  "Draw a plant you can see from life",
  "Touch the bark of a tree and notice its texture",
  "Find the largest fallen leaf you can",
  "Find the smallest intact fallen leaf you can",
  "Photograph three different leaf shapes",
  "Find a plant growing somewhere unexpected",
  "Watch an insect for one uninterrupted minute",
  "Find a spiderweb and observe it without touching it",
  "Look for animal tracks or other signs that an animal passed through",
  "Stand still outside and identify bird sounds before looking for the birds",
  "Find and photograph a repeating pattern in nature",
  "Photograph something naturally yellow",
  "Photograph something naturally red",
  "Photograph something naturally purple",
  "Find something in the real world that resembles a face",
  "Choose a small rock you like and give it a ridiculous name",
  "Stack three rocks without using glue or supports",
  "Draw a tiny face on a rock with a washable or appropriate marker",
  "Paint a kindness message on a rock and place it somewhere appropriate",
  "Collect one fallen leaf you find interesting and press it inside a book",
  "Smell one flower and try to describe the scent in words",
  "Identify one wild or garden plant you have never noticed before",
  "Find out whether one plant near you is native to your region",
  "Find and photograph something in nature smaller than your fingernail",
  "Spend three minutes looking at the moon",
  "Take a photograph of the moon without worrying whether it looks impressive",
  "Watch the sky continuously while it changes color around sunrise or sunset",
  "Find one cloud that resembles an object or animal and give it a name",
  "Spend ten minutes outside after dark",
  "Sit somewhere dry and listen to rainfall for five minutes",
  "Walk through a puddle on purpose while wearing appropriate shoes",
  "Catch a snowflake on your glove or sleeve if it is snowing",
  "Stand still and pay attention to the wind for one minute",
  "Watch tree branches move in the wind for three minutes",
  "Find a place where plants are growing through or around something human-made",
  "Visit a public park you have not visited recently",
  "Walk around one block you have never fully explored",
  "Take a safe street or path you normally ignore",
  "Find one piece of public art in your area",
  "Photograph a mural you like",
  "Stop and read an entire historical marker or plaque",
  "Find the oldest-looking building within walking distance and look up its age",
  "Spend five minutes noticing architectural details above eye level",
  "Spend five minutes noticing details close to the ground",
  "Find and photograph an interesting door",
  "Find a building painted a color you would never choose",
  "Find a building color combination you unexpectedly like",
  "Count the dogs you see during a fifteen-minute walk",
  "Wave hello to one neighbor",
  "Introduce yourself to someone you see regularly but have never met",
  "Learn the name of one neighbor you did not know before",
  "Bring in a neighbor's empty trash bin if appropriate and welcome",
  "Pick up visible litter on one section of your street",
  "Return one abandoned shopping cart to the proper place",
  "Straighten one messy shared area without being asked",
  "Leave one public or shared space cleaner than you found it",
  "Thank a worker by name if their name is visible or known",
  "Let someone with fewer items go ahead of you in a checkout line",
  "Offer someone the better seat",
  "Hold an elevator or door for someone approaching",
  "Offer to carry something for someone who could use the help",
  "Alert someone if you notice they dropped something",
  "Return a lost object to an appropriate lost-and-found location",
  "Submit positive feedback about an employee who helped you",
  "Recommend a small local business to someone",
  "Thank someone whose work often goes unnoticed",
  "Send a former teacher or mentor a brief thank-you message",
  "Thank a coworker for one specific thing they do well",
  "Tell a friend one quality that makes them a good friend",
  "Tell a family member about a memory involving them that you treasure",
  "Ask an older relative or acquaintance what their childhood neighborhood was like",
  "Ask a younger person what they are most excited about right now",
  "Listen to someone describe a problem without immediately offering advice",
  "Ask someone what they are currently trying to learn",
  "Ask someone what song they currently have on repeat and listen to it later",
  "Send a friend a meme chosen specifically for their sense of humor",
  "Share a photograph that reminds you of someone with that person",
  "Check in on someone you have not heard from lately",
  "Congratulate someone on a small accomplishment",
  "Give a genuine apology for one small thing you regret",
  "Choose one minor annoyance you are willing to let go",
  "Assume good intent once when a harmless misunderstanding happens",
  "Replace one unnecessary apology with a sincere \"thank you.\"",
  "Politely decline one optional thing you genuinely do not want to do",
  "Say yes to one harmless opportunity you usually dismiss automatically",
  "Ask someone for help with one small task",
  "Offer someone help with one small task",
  "Return one borrowed item",
  "Lend someone something useful that you are comfortable lending",
  "Teach someone one simple thing you know how to do",
  "Ask someone to teach you one simple thing they know how to do",
  "Ask someone about a hobby they genuinely love and let them explain it",
  "Introduce two people who share an interest and might enjoy knowing each other",
  "Send someone a short voice message instead of typing",
  "Call someone solely to say hello",
  "Tell someone you miss spending time with them",
  "Tell someone you are proud of something they did",
  "Tell someone one specific way they made your day better",
  "Leave a handwritten note somewhere a housemate or family member will find it",
  "Hide a tiny drawing in someone's lunch or bag",
  "Make someone a cup of coffee, tea, or another drink",
  "Bring someone a glass of water without being asked",
  "Share a snack with someone",
  "Give someone the last piece of something you both enjoy",
  "Ask someone whether they need anything while you are already getting up",
  "Do one household chore that someone else usually handles",
  "Find one small way to make another person's day easier",
  "Write down one thing you have been avoiding and work on it for five minutes",
  "Finish one task that is almost complete",
  "Cross one lingering task off your to-do list by actually completing it",
  "Delete one task from your to-do list because it no longer matters",
  "Break one intimidating task into three clearly defined steps",
  "Complete the easiest step of one intimidating task",
  "Set a ten-minute timer and tidy one room until the timer ends",
  "Clear every unnecessary item off one horizontal surface",
  "Empty one trash can",
  "Take your recycling to the proper bin",
  "Gather all loose dirty laundry into one place",
  "Fold and put away ten pieces of clean laundry",
  "Match every loose sock you can find",
  "Throw away or repurpose one lonely sock you know is never finding its partner",
  "Hang up every piece of clothing currently sitting on one chair",
  "Completely clean one corner of a room",
  "Vacuum or sweep one small area",
  "Wipe down one section of baseboard",
  "Dust one lamp or lampshade",
  "Clean three light switches",
  "Disinfect your remote control",
  "Clean five frequently touched handles or knobs",
  "Clear unnecessary products off your bathroom counter",
  "Throw away empty or unusable toiletries",
  "Replace one empty household supply such as toilet paper, soap, or tissues",
  "Wash one set of towels",
  "Remove hair and debris from your hairbrush",
  "Throw away one object you have kept for no sensible reason",
  "Repair one small broken household item",
  "Tighten one visibly loose screw on something you use",
  "Replace one dead household battery",
  "Gather loose spare batteries into one labeled place",
  "Gather loose coins into one container",
  "Empty every pocket before starting your next load of laundry",
  "Completely clean out one handbag, backpack, or tote",
  "Remove all trash from one backpack or work bag",
  "Clean the cup holders in your car",
  "Remove five unnecessary items from your car",
  "Put one useful emergency item in your car",
  "Check the tire pressure on your vehicle if you have access to a gauge",
  "Refill one household item that is nearly empty",
  "Replace one small item you have been putting off replacing",
  "Label one container whose contents are currently confusing",
  "Put one important paper document somewhere safe and logical",
  "Photograph or scan one receipt you may need later",
  "Throw away one expired coupon or obsolete offer",
  "Cancel one free trial you do not intend to keep",
  "Review one subscription and decide whether it is still worth paying for",
  "Turn off notifications from one app that interrupts you unnecessarily",
  "Remove one app from your phone's home screen to reduce clutter",
  "Organize similar phone apps into one folder",
  "Change your lock screen to an image you genuinely enjoy",
  "Delete one duplicate or obsolete contact from your phone",
  "Add missing information to one important contact",
  "Make sure at least one trusted person is listed as an emergency contact on your phone",
  "Close twenty browser tabs you no longer need",
  "Bookmark one online resource you genuinely want to return to",
  "Delete five browser bookmarks you no longer use",
  "Organize ten files from your computer desktop",
  "Empty your computer's trash or recycle bin after checking the contents",
  "Delete ten obvious junk emails",
  "Reply to one message you have been unnecessarily avoiding",
  "Archive one old digital conversation you no longer need visible",
  "Save one important photograph somewhere backed up",
  "Rename one important digital file so it is easy to find later",
  "Digitize one paper you do not need to keep physically",
  "Correct or remove one outdated calendar entry",
  "Add one important birthday to your calendar",
  "Schedule one appointment or task you keep forgetting",
  "Set one reminder that will genuinely help your future self",
  "Delete one obsolete reminder",
  "Write down your three highest priorities for tomorrow",
  "Choose one most-important task for today and finish it before adding another",
  "Work on one task with full focus for fifteen minutes",
  "Put your phone in another room while completing one focused task",
  "Close every unrelated computer tab before beginning one task",
  "Clear enough space on your desk to work comfortably",
  "Put a full glass or bottle of water next to your workspace",
  "Adjust your chair and screen so your posture feels better",
  "Stand up and stretch after a long period of sitting",
  "Look at something far away for twenty seconds to rest your eyes",
  "Take a ten-minute break from all screens",
  "Adjust your screen brightness to a comfortable level",
  "Clean your computer mouse or trackpad",
  "Organize one paper notebook",
  "Remove loose or useless papers from one notebook or binder",
  "Start a fresh notebook page with today's date and write whatever is on your mind",
  "Do a five-minute brain dump of every task on your mind",
  "Choose the single most important item from your current to-do list",
  "Write one current problem in a single clear sentence",
  "Write three possible solutions to one current problem",
  "Try the easiest reasonable solution to one small current problem",
  "Ask if one current worry will matter a year from now",
  "Write down one completed task you have not given yourself credit for",
  "Learn one fact today that you genuinely did not know yesterday",
  "Teach someone one interesting fact you recently learned",
  "Look up the origin or meaning of your last name",
  "Learn the traditional meaning or history of your first name",
  "Learn why your city, town, or neighborhood has its name",
  "Look up the origin of one local street name",
  "Read about one historical event that occurred on today's calendar date",
  "Learn about one notable person who shares your birthday",
  "Learn what one symbol on a national or regional flag represents",
  "Locate five unfamiliar countries on a map",
  "Memorize the capital of one country you could not name before",
  "Learn one useful word in another language and say it aloud five times",
  "Learn how to count from one to ten in another language",
  "Practice spelling one word you frequently misspell",
  "Learn the difference between two English words you often confuse",
  "Read one complete short essay",
  "Read one complete short story",
  "Read one comic or graphic story you have never read before",
  "Read something written before you were born",
  "Read one thoughtful argument from a viewpoint different from your own",
  "Find one point you can understand in an opinion you disagree with",
  "Learn how one object within arm's reach works",
  "Learn how a zipper mechanically opens and closes",
  "Learn why the daytime sky appears blue",
  "Learn why leaves change color in autumn",
  "Learn what physically causes thunder",
  "Learn one new fact about the human body",
  "Learn one basic first-aid skill from a trustworthy source",
  "Learn the common warning signs of a stroke",
  "Locate the nearest fire extinguisher in a building you use regularly",
  "Check whether one smoke detector in your home appears operational",
  "Find and save your local non-emergency police or municipal service number",
  "Memorize one important phone number you currently rely on your phone to remember",
  "Determine which direction north is from your home",
  "Find the closest public library to where you live",
  "Browse a library shelf from a subject area you normally ignore",
  "Borrow a physical or digital library item",
  "Return one library item you have finished using",
  "Learn one new shortcut in software you use regularly",
  "Watch one short educational video and immediately try what it teaches",
  "Learn one simple drawing technique and practice it for ten minutes",
  "Learn how to draw a three-dimensional cube by hand",
  "Practice drawing a simple human face",
  "Draw one recognizable object using only circles",
  "Draw one recognizable object using only straight lines",
  "Draw the room you are in from memory before looking around",
  "Spend ten minutes drawing the view from a nearby window",
  "Draw one object in exactly sixty seconds",
  "Draw one ordinary object carefully for ten uninterrupted minutes",
  "Fill one entire sheet of paper with tiny unrelated doodles",
  "Design a fictional company logo",
  "Design a personal flag using three symbols that represent you",
  "Invent a fictional country and give it a name, flag, and capital",
  "Draw a map of a completely imaginary island",
  "Invent a new holiday and write down three traditions people would follow",
  "Create a menu for a fictional restaurant",
  "Invent the worst restaurant and write it a glowing review",
  "Write a fake newspaper headline describing your day",
  "Turn one boring thing that happened today into a dramatic breaking-news report",
  "Write a two-sentence horror story",
  "Write a two-sentence romance",
  "Write a complete story using exactly fifty words",
  "Write a short paragraph without using the letter E",
  "Give your day a movie title",
  "Choose three actors who would play people from your life in a movie",
  "Choose five songs that would belong on the soundtrack of your life",
  "Draw a movie poster for your day",
  "Make a tiny collage using scrap paper or old packaging",
  "Cut a paper snowflake",
  "Make a folded-paper fortune teller and fill it with positive fortunes",
  "Make a paper chain from scrap paper",
  "Fold a paper crown and wear it for five minutes",
  "Build something recognizable from cardboard",
  "Turn an empty box into something amusing or useful",
  "Make a small sculpture using recyclable materials",
  "Create a piece of art from something you were about to throw away",
  "Decorate an ordinary envelope",
  "Write a handwritten letter to someone",
  "Make yourself a ridiculous achievement certificate and sign it",
  "Invent an award and give it to someone who deserves it",
  "Build a tiny trophy from household objects",
  "Draw a one-panel cartoon about something that happened today",
  "Invent a cartoon character and give the character a name and personality",
  "Draw one fictional character in a terrible morning and a great evening",
  "Make a simple flipbook animation using a small stack of paper",
  "Create a custom bookmark for the book you are currently reading",
  "Put on one song and dance until it ends",
  "Learn one simple dance move",
  "Attempt a moonwalk somewhere you have enough safe space",
  "Balance on one foot while brushing your teeth if it feels safe",
  "Walk backward ten slow steps in a clear safe space",
  "Take the stairs instead of an elevator for one trip if physically comfortable",
  "Add one extra block to a normal walk",
  "Stretch both calves for thirty seconds each",
  "Stretch both hamstrings gently",
  "Spend one minute stretching your wrists and hands",
  "Roll your shoulders slowly ten times in each direction",
  "Reach both arms overhead and stretch for twenty seconds",
  "Reach toward your toes for thirty comfortable seconds",
  "Do ten slow controlled squats",
  "Do ten comfortable lunges while holding onto support if needed",
  "Do ten wall push-ups",
  "Hold a plank for as long as feels comfortable",
  "Follow a five-minute beginner yoga routine",
  "Walk around during one phone call",
  "Walk continuously for the duration of one favorite song",
  "Take a movement break before watching your next episode of television",
  "Stand instead of sitting during one phone call",
  "Practice standing up from a chair five times without using your hands if comfortable",
  "Balance a lightweight book on your head while walking ten steps",
  "Toss a rolled-up sock into a basket from increasingly farther away",
  "Play catch with another person for five minutes",
  "Kick a ball around for ten minutes",
  "Make two paper airplanes, one designed for distance and one designed for accuracy",
  "Time yourself walking one familiar block at a brisk but comfortable pace",
  "Walk a familiar route deliberately slowly and notice details you usually miss",
  "Take a ten-minute walk focused entirely on sounds",
  "Take a ten-minute walk focused entirely on visual details",
  "Take one walk without headphones",
  "Listen to an entire album while walking",
  "Dance while completing one household chore",
  "Stretch while waiting for water to boil, food to heat, or another short delay",
  "Do twenty calf raises while brushing your teeth or waiting at a counter",
  "Shake out your arms and legs for thirty seconds",
  "Spend one minute deliberately improving your posture",
  "Relax your jaw and face for one full minute",
  "Drop your shoulders from your ears and hold that for thirty seconds",
  "Unclench your hands whenever you notice tension and keep them relaxed for one minute",
  "Take five slow breaths through your nose",
  "Take five breaths where each exhale lasts longer than each inhale",
  "Sit somewhere comfortable and do nothing for five minutes",
  "Give yourself ten minutes of genuine rest without trying to accomplish anything",
  "Go to bed when you first notice you are genuinely sleepy",
  "Make your sleeping area darker than usual tonight",
  "Put your phone somewhere you cannot reach from bed",
  "Drink a full glass of water soon after waking",
  "Open your curtains or blinds soon after waking",
  "Spend five minutes in outdoor morning light",
  "Wash your face slowly instead of rushing",
  "Moisturize one area of dry skin",
  "Trim and clean your fingernails",
  "Take one unhurried shower",
  "Finish a shower with thirty seconds of cooler water if comfortable",
  "Put on clean clothes simply because they feel good",
  "Wear something nice that you have been saving for a special occasion",
  "Use one \"special occasion\" item on an ordinary day",
  "Spend five minutes caring for an object you want to keep for a long time",
  "Polish or carefully clean one possession you value",
  "Mend one small tear in fabric",
  "Sew one loose button securely back onto clothing",
  "Learn how to sew on a button",
  "Clean one pair of shoelaces",
  "Empty and clean one coat or pants pocket that has accumulated junk",
  "Clear one place in your home where random objects constantly pile up",
  "Put away as many misplaced items as possible in exactly five minutes",
  "Light a candle and sit nearby for five minutes if candles are safe where you are",
  "Spend fifteen minutes using softer lighting than usual",
  "Put on relaxing instrumental music for ten minutes",
  "Listen closely to one instrumental song with your eyes closed",
  "Listen to a familiar song and identify an instrument you never noticed before",
  "Listen to one song in a language you do not understand and look up what it is about",
  "Find a cover version of a song you love and compare it with the original",
  "Make a three-song playlist for rainy weather",
  "Make a three-song playlist for a road trip",
  "Make a three-song playlist for feeling confident",
  "Make a three-song playlist specifically for doing nothing",
  "Listen to one song you loved when you were fifteen",
  "Listen to one song someone who raised you loved",
  "Find the oldest recording you can genuinely enjoy",
  "Listen to three songs from a musician you have never heard before",
  "Listen to one complete piece of classical music",
  "Listen to one movie score without watching the movie",
  "Choose one song as the official theme song for today",
  "Take exactly one photograph that represents your day",
  "Photograph one ordinary object as beautifully as you can",
  "Photograph one conventionally ugly object as beautifully as you can",
  "Photograph the same object from five dramatically different angles",
  "Take one photograph from directly overhead",
  "Take one photograph with your camera nearly touching the ground",
  "Take one photograph framed through a doorway",
  "Take one photograph where the main subject is a reflection",
  "Take one photograph where the subject appears primarily as a silhouette",
  "Take a close-up photograph focused on texture",
  "Photograph the smallest interesting object you can find",
  "Photograph something so large it barely fits in the frame",
  "Photograph something temporary that will not look the same tomorrow",
  "Photograph one object you see almost every day",
  "Photograph one detail you have never noticed before",
  "Take a black-and-white photograph",
  "Take a portrait or still-life photograph using only natural light",
  "Take one photograph where a single color dominates the frame",
  "Re-create one old photograph as closely as you reasonably can",
  "Photograph the shoes you are wearing today",
  "Arrange the contents of your pockets or bag and photograph them",
  "Photograph your next meal before eating it",
  "Take one photograph of exactly what you can see at noon",
  "Make a complete three-photo visual story with a beginning, middle, and end",
  "Create a five-item photography scavenger hunt and complete it yourself",
  "Find and photograph something perfectly round",
  "Find and photograph a triangle occurring in everyday life",
  "Find and photograph something striped",
  "Find and photograph something rusty",
  "Find and photograph something handwritten",
  "Find one object that is more than fifty years old",
  "Find a typo on a sign, package, menu, or website",
  "Find and photograph something that accidentally looks like a face",
  "Find an interesting number in your surroundings and invent a meaning for it",
  "Find your initials somewhere outside your own belongings",
  "Find examples of all seven rainbow colors during one day",
  "Find something smaller than a coin and examine it closely",
  "Find something nearby that is much taller than you",
  "Find one object that has clearly been repaired instead of replaced",
  "Find one everyday object with a tiny design detail someone cared about",
  "Find one badly designed everyday object and sketch one improvement",
  "Find one brilliantly designed everyday object and write down why it works",
  "Notice five different typefaces or lettering styles in your surroundings",
  "Read an entire sign you have passed many times without reading",
  "Look at the back side of a familiar building and notice how different it feels",
  "Find one small detail in a familiar place that you had never noticed",
  "Write down one thing you are overcomplicating and the simplest next step",
  "Make one minor decision you have been postponing",
  "Stop researching one low-stakes decision and choose an option",
  "Think about one worry for ten minutes, then switch to something useful",
  "Write down only the parts of one problem that are genuinely within your control",
  "Lower one unnecessary personal expectation for today",
  "Finish one task at a \"good enough\" level instead of trying to make it perfect",
  "Share or use one thing you created instead of endlessly adjusting it",
  "Ask yourself what would make today easier and do one reasonable thing from the answer",
  "Write down one personal boundary you want to communicate more clearly",
  "Practice saying one difficult but reasonable boundary out loud",
  "Write down one hard thing you handled better than you admit",
  "Write down one mistake and the most useful thing it taught you",
  "Name one skill you have improved during the last five years",
  "Choose one skill you want to improve and practice it for ten minutes",
  "Write down one fear that has become smaller with time",
  "Do one mildly uncomfortable but useful thing you have been avoiding",
  "Ask one question you have been embarrassed to ask",
  "Admit that you do not know something and spend five minutes learning about it",
  "Look up evidence about one belief you are uncertain about",
  "Catch one assumption you are making today and check whether it is actually true",
  "Turn one complaint you have into one concrete action you can take",
  "Fix one small annoyance that you have tolerated for too long",
  "Stop using one approach that clearly is not working and try a simpler one",
  "Try the obvious solution to one small problem before a complicated one",
  "Write a list of five things you do not actually need to accomplish this week",
  "Remove one unnecessary obligation from your schedule if you are free to do so",
  "Spend ten minutes doing something solely because you enjoy it",
  "Try a harmless skill you are bad at and allow the result to be bad",
  "Retry one thing you recently failed at",
  "Write a ridiculous description of one issue you are taking too seriously",
  "Write the worst solution to a harmless problem, then a better one",
  "Ask \"What would make this easier?\" about one task and actually simplify the task",
  "Ask yourself what you are waiting for before starting one small project",
  "Begin one small project before you feel completely ready",
  "Flip a coin between two low-stakes options and follow it",
  "Roll a die and take a walk lasting that many minutes",
  "Open a random book to page forty-two and read the whole page",
  "Open a dictionary to a random page and learn the first unfamiliar word you see",
  "Shuffle your music library and listen to the first song without skipping",
  "Let someone else choose what movie, show, or game you try",
  "Number several acceptable meal options and choose one using a random number",
  "Take the next unfamiliar safe turn during a walk and explore for five minutes",
  "Choose one color and look for examples of it throughout the day",
  "Pick a number from one to ten and find that many interesting objects outside",
  "Write five tiny challenges on scraps of paper, mix them up, and complete one at random",
  "Put a mystery on your calendar without deciding what it is yet",
  "Hide a small treat or dollar for your future self to discover",
  "Hide a positive note somewhere another person will eventually find it",
  "Leave a handwritten message inside a book you own for your future self",
  "Seal a note to yourself in an envelope labeled with a future opening date",
  "Make a tiny time capsule with three things that represent your life now",
  "Write a one-paragraph prediction of your life one year from now",
  "Write one absurd prediction about something that might happen this week",
  "Guess tomorrow's weather before checking a forecast and write down your guess",
  "Estimate how many people you will speak with tomorrow and write down the number",
  "Choose one harmless activity today entirely because it sounds fun",
  "Try a flavor of food or drink you usually ignore",
  "Choose something different from your usual order or recipe",
  "Read one magazine article chosen mostly at random",
  "Watch a movie you know almost nothing about, no plot recap first",
  "Start a book without checking its online rating",
  "Try one recommendation from a friend without researching it to death first",
  "Ask a friend to invent one small harmless challenge for you and complete it",
  "Give a friend one harmless challenge they can finish in fifteen minutes",
  "Make a zero-stakes bet with yourself about something that will happen today",
  "Flip a coin. Heads, create for ten minutes. Tails, clean for ten minutes",
  "Pick a random letter and find five nearby objects starting with it",
  "Pick a random country and learn five facts about it",
  "Pick a random year from the last century and learn one major event from that year",
  "Pick a random animal, draw it from memory, then look at a real picture and compare",
  "Find one free public activity available in your area sometime this week",
  "Visit a public place you have passed but never entered",
  "Browse one section of a bookstore or library you normally ignore",
  "Walk a thrift store and find the strangest object without buying it",
  "Visit a park you have never been to before",
  "Sit in a different seat than you normally choose",
  "Move one small piece of furniture and decide whether the new arrangement works better",
  "Eat one meal in a different place than usual",
  "Work or read somewhere different for twenty minutes",
  "Spend ten minutes in a part of your home you rarely use",
  "Use a different entrance to a familiar building if it is publicly accessible",
  "Change one part of your normal routine and notice how it affects your day",
  "Brush your teeth using your nondominant hand",
  "Use your nondominant hand for opening doors for ten minutes",
  "Write one sentence backward, letter by letter, then try reading it in a mirror",
  "Draw one ordinary object upside down",
  "Read two pages of a book while standing",
  "Lie on the floor and listen to one entire song",
  "Watch one familiar movie scene with the sound muted and guess the dialogue",
  "Watch ten minutes of something with subtitles turned on",
  "Memorize one line from a movie you love",
  "Re-create one movie shot using household objects",
  "Narrate one boring chore as if it were a dramatic nature documentary",
  "Invent an elaborate fictional history for one ordinary object",
  "Give a household appliance or plant a name and write a tiny biography for it",
  "Make a serious top-ten ranking of ten completely mundane objects",
  "Rank five spoons, mugs, or similar household items and declare one the champion",
  "Photograph the weirdest object in your home like a luxury product",
  "Write an absurd advertisement for an ordinary household item",
  "Invent a completely useless product and draw a prototype",
  "Invent a terrible advertising slogan and then rewrite it into a good one",
  "Invent a secret society with a name, symbol, and one ridiculous rule",
  "Create a harmless secret code word and use it naturally once today",
  "Write a fake fortune-cookie message and give it to someone",
  "Write down one prediction for tomorrow and check later whether it happened",
  "Turn one ordinary moment today into a memory by photographing or writing about it",
  "Write one sentence you would want to remember about today",
  "Write today's date on one physical object or page you plan to keep",
  "Save one tiny object that represents this month and label it with the date",
  "Record ten seconds of ambient sound from where you are",
  "Record a thirty-second audio description of your surroundings",
  "Record a short message for your future self",
  "Ask someone you care about one question you have never asked them before",
  "Write down one family story you do not want to disappear",
  "Ask someone for a recipe that has personal meaning to them and write it down",
  "Ask someone older than you what they were like at your age",
  "Ask someone what their first paying job was",
  "Ask someone what they wanted to be when they were a child",
  "Ask someone to describe the best trip they have ever taken",
  "Ask someone what advice they once ignored but later realized was useful",
  "Tell someone about a shared memory they may have forgotten",
  "Look at a photo from five years ago and remember how life felt then",
  "Write down one thing you worried about years ago that no longer matters",
  "Find one thing you have owned over ten years and decide if you still want it",
  "Write the story behind one sentimental object",
  "Label one old photograph with names, place, and approximate date",
  "Organize ten old photographs into a folder or album",
  "Send one old photograph to someone who appears in it",
  "Rewatch one movie you loved as a child",
  "Reread one children's book you once loved",
  "Make a snack you remember from childhood",
  "Play a game you have not played in years",
  "Make a drawing using crayons",
  "Color something without trying to stay inside the lines",
  "Blow soap bubbles if you have access to bubble solution",
  "Build a blanket fort",
  "Sit underneath a table for five minutes and experience the room from there",
  "Build a comfortable pile of pillows and sit in it",
  "Skip instead of walking for ten safe seconds",
  "Use a playground swing if one is available and appropriate for adults",
  "Roll down a gentle grassy hill if conditions are safe",
  "Make a small craft using fallen leaves or flowers without damaging live plants",
  "Draw something temporary with sidewalk chalk where permitted",
  "Play a best-of-seven game of tic-tac-toe with someone",
  "Play a best-of-seven round of rock-paper-scissors",
  "Make a five-item scavenger hunt for someone else",
  "Hide a harmless object and draw a simple treasure map leading to it",
  "Make yourself a paper badge declaring you champion of something absurdly specific",
  "Try the smallest version of something you have always wanted to learn",
  "Start reading the book you keep saying you will read",
  "Watch the movie you keep saying you will eventually watch",
  "Write on the first page of a notebook you have been saving",
  "Use art supplies you have been saving for the \"right\" project",
  "Wear one piece of clothing you have been saving for a special occasion",
  "Cook one recipe you bookmarked a long time ago",
  "Send one kind or useful message you have been repeatedly composing in your head",
  "Display one object or picture you love instead of keeping it stored away",
  "Fix one tiny inconvenience in your home that has been annoying you for weeks",
  "Move one frequently used object closer to where you actually use it",
  "Recycle or throw away one empty package you have inexplicably kept",
  "Finish one nearly empty household product before opening another",
  "Straighten one crooked picture, sign, or decoration",
  "Sharpen every dull pencil you regularly use",
  "Test your pens and discard or recycle the ones that no longer work",
  "Write one page using your favorite pen",
  "Write your next to-do list by hand instead of typing it",
  "Put one thought that feels important onto actual paper",
  "Do one small task that tomorrow-you will appreciate",
  "Prepare one thing tonight that will make tomorrow morning easier",
  "Put one object you need tomorrow beside the door",
  "Fill a water bottle so it is ready for later",
  "Charge one electronic device before its battery becomes critically low",
  "Check on someone before they need to ask for help",
  "Say one kind thought aloud instead of keeping it to yourself",
  "Publicly give someone appropriate credit for something they contributed",
  "Give someone useful constructive feedback privately and kindly",
  "Accept one compliment today without arguing against it",
  "Thank someone sincerely when they compliment you",
  "Notice one thing that goes unexpectedly well and say so out loud",
  "Celebrate completing one small task instead of immediately moving to the next",
  "Photograph the finished result of something you worked on",
  "Write down one small win from today",
  "Choose one thing about this week that you want to remember",
  "Write down one thing from this week you are ready to stop carrying forward",
  "Make yourself one small promise you can realistically keep today and keep it",
  "Spend five minutes improving the space immediately around you",
  "Spend five minutes improving a shared space for other people",
  "Spend exactly five minutes learning about a subject that interests you",
  "Spend exactly five minutes making something with your hands",
  "Spend exactly five minutes moving your body",
  "Spend exactly five minutes outdoors",
  "Spend fifteen minutes doing something purely because you enjoy it",
  "Write down one thing you are curious about and research the answer",
  "Learn the name of one person you regularly see but have never properly met",
  "Ask someone for their favorite joke",
  "Learn one joke well enough to tell it without reading it",
  "Write a one-line joke about something in the room",
  "Invent a nickname for an ordinary object you use every day",
  "Rearrange the icons on one phone screen so the useful ones are easiest to reach",
  "Delete one saved note you no longer need",
  "Organize ten saved notes into useful categories",
  "Clear ten completed items from a reminders app",
  "Change one unnecessary recurring alarm",
  "Set your alarm ten minutes earlier on one morning and use the extra time deliberately",
  "Leave home ten minutes earlier than necessary for one routine trip",
  "Walk around a store once before buying anything",
  "Buy nothing during one casual shopping trip",
  "Compare the price of one product you regularly buy across two stores or websites",
  "Find one household item you can reuse instead of replacing",
  "Repair or creatively reuse one object you might otherwise discard",
  "Make a reusable shopping list of items you buy frequently",
  "Count how many reusable bags you own and put them somewhere useful",
  "Bring a reusable cup, bottle, or bag on one outing",
  "Use both sides of one piece of scrap paper",
  "Save one clean container for a practical reuse",
  "Remove one item from your online shopping cart that you do not really want",
  "Wait twenty-four hours before making one nonessential purchase",
  "Put the cost of one skipped impulse purchase into savings if practical",
  "Count all the loose change you can find in your home",
  "Check one receipt for a purchase you made recently",
  "Look at one bill you usually ignore and make sure you understand it",
  "Review one automatic payment so you know what it is for",
  "Cancel one recurring charge you no longer value",
  "Make a list of three free activities you genuinely enjoy",
  "Spend one hour without spending any money",
  "Prepare one snack to bring with you instead of buying one later",
  "Fill a water bottle before leaving home",
  "Borrow one item instead of buying it if borrowing is easy and appropriate",
  "Write one expensive thing you want and three free ways to scratch the itch",
  "Do one nice thing for your home using only things you already own",
  "Rearrange a shelf using only objects already on it",
  "Create a tiny display of three objects you like",
  "Put a neglected photograph where you can see it",
  "Rotate one piece of art or decoration to a different room",
  "Clear one small area completely and leave it intentionally empty",
  "Choose one possession you genuinely love and clean it",
  "Choose one possession you dislike and decide whether you can let it go",
  "Put one seasonal item back into proper storage",
  "Open one storage box and identify everything inside",
  "Label one storage box clearly",
  "Combine two half-empty containers of the same household product",
  "Fold reusable bags neatly into one place",
  "Organize all charging cables in one location",
  "Find one mystery cable and determine what it belongs to",
  "Recycle one obsolete electronic accessory through an appropriate program",
  "Check one device for an available software update",
  "Restart one device you have not restarted in a long time",
  "Clean one pair of earbuds or headphones safely",
  "Listen to one voicemail you have been avoiding",
  "Delete old voicemails you no longer need",
  "Save one important voicemail or audio message somewhere safe",
  "Record your own voice reading a favorite paragraph",
  "Record one minute of sounds from your neighborhood",
  "Listen to one minute of silence with headphones off",
  "Turn off background television or audio for fifteen minutes",
  "Spend one hour without algorithmic scrolling",
  "Log out of one app that you open reflexively",
  "Move one distracting app off your main phone screen",
  "Set one reasonable app limit for a distraction you want to reduce",
  "Choose one hour today to keep your phone on silent",
  "Leave your phone behind while walking around your home or yard for ten minutes",
  "Put your phone face down during one entire conversation",
  "Take one photograph and resist checking it immediately",
  "Look through ten photographs without editing or deleting any of them",
  "Print one digital photo eventually worth keeping physically",
  "Write the names of people pictured on the back of one printed photo",
  "Create a folder containing your ten favorite photos from this year",
  "Choose one photograph as your favorite image of the month",
  "Write down the story behind one recent photograph",
  "Take one picture of something you normally would never think to photograph",
  "Photograph one thing that represents your current mood without including your face",
  "Photograph one object that represents someone you care about",
  "Make a three-image collage from photographs you already have",
  "Write one caption for a photograph without posting it anywhere",
  "Write a five-sentence description of the room you are currently in",
  "Describe one familiar object as if the reader has never seen one before",
  "Write one paragraph using only simple one-syllable words as much as possible",
  "Write one paragraph describing a place entirely through sounds",
  "Write one paragraph describing a memory entirely through smells and textures",
  "Write one short scene in which nobody speaks",
  "Write a conversation between two household objects",
  "Write a letter from your pet, plant, car, or favorite object to you",
  "Write five alternative titles for your current week",
  "Invent a fictional weather forecast for your mood",
  "Give today a rating out of ten and write one sentence explaining the score",
  "Write down one thing that could make tomorrow one point better",
  "Choose one tiny thing to look forward to tomorrow",
  "Do one favor for your future self before bed",
  "Tell one person something you admire about the way they handle life",
  "Ask someone what they are looking forward to this month",
  "Share one useful thing you learned recently with someone who could benefit from it",
  "Recommend one free resource that has helped you",
  "Thank someone for something they did so long ago they may have forgotten it",
  "Leave one situation slightly better than you found it",
  "Finish one thing today instead of starting another",
  "Choose one ordinary moment today and give it your full attention",
  "Do one small thing today that makes a good story later",
  "Do one small thing today that your future self will be glad happened",
];
