export const HOUSE_DECK = [
  'Send the email you have been sitting on',
  'Do the smallest version of the thing',
  'Take a 12-minute walk',
  'Drink a glass of water',
  'Text them',
  'Do not text them',
  'Start it for ten minutes and stop if you want',
  'Go outside',
  'Eat something',
  'Put the phone in another room for 20 minutes',
  'Call instead of typing',
  'Pick the cheaper option',
  'Pick the sooner date',
  'Close the extra tabs',
  'Backup the file',
  'Ask one person',
  'Say no',
  'Say yes',
  'Leave 15 minutes earlier than you think',
  'Write the ugly first draft',
  'Delete the extra take and ship',
  'Confirm it in writing',
  'Go to bed',
  'Stretch your neck',
  'Clear the sink',
  'Make the reservation',
  'Pay the thing',
  'Stand up and reset the room',
];
