export const HOUSE_DECK = [
  "Write a thank you",
  "Feed a bird",
  "Scream into the void",
  "Send the email you have been sitting on",
  "Do the smallest version of the thing",
  "Drink a glass of water",
  "Take a 12-minute walk",
  "Text someone you are glad they exist",
  "Tell someone they were right",
  "Write the apology you owe",
  "Leave a kind comment",
  "Hold the door and mean it",
  "Let someone go first",
  "Return the shopping cart",
  "Compliment a stranger",
  "Check on someone you went quiet on",
  "Thank the person who does the invisible work",
  "Leave a generous review",
  "Wave at a neighbor",
  "Ask someone how they actually are and wait",
  "Forgive the small thing",
  "Give away one object",
  "Write a note and leave it for someone",
  "Tip extra if you can",
  "Tell a friend one specific thing you like about them",
  "Reply to the message you keep opening",
  "Invite someone to something small",
  "Listen without planning your answer",
  "Make room on the sidewalk",
  "Pick up the thing someone dropped",
  "Return what you borrowed",
  "Say the name of the person helping you",
  "Send a photo of something ordinary and nice",
  "Write a recommendation",
  "Celebrate someone else's win out loud",
  "Let the other car in",
  "Put a kind sticky note where someone will find it",
  "Mail a postcard",
  "Clap for a street musician",
  "Tell the cook it was good",
  "Leave the last of something for the next person",
  "Teach someone a shortcut you know",
  "Ask a quiet person a real question",
  "Remember a birthday on purpose",
  "Send the song to the one person who would love it",
  "Write a thank you to a teacher, even late",
  "Thank your past self for one thing",
  "Send a voice note instead of a paragraph",
  "Save a seat for someone",
  "Offer to help carry the awkward thing",
  "Text that you got home safe",
  "Say good morning out loud",
  "Look someone in the eye when you thank them",
  "Tell the truth about a small thing",
  "Ask for the thing you want, plainly",
  "Say no without a speech",
  "Say yes to the small invitation",
  "Introduce yourself to someone you see often",
  "Learn the name of the person at the counter",
  "Hold the elevator",
  "Give someone the benefit of the doubt",
  "Delete the mean reply you drafted",
  "Wish someone luck and mean it",
  "Send the recipe",
  "Share the umbrella",
  "Point out the good haircut",
  "Write a letter you do not have to send",
  "Leave a book in a public place",
  "Help someone with a bag on the stairs",
  "Make the extra portion",
  "Ask to hear the story again and listen better",
  "Forgive yourself for yesterday",
  "Sit with someone who is waiting",
  "Pass along a compliment you heard",
  "Return the extra change",
  "Leave a light on for the person coming later",
  "Keep a secret that is not yours to tell",
  "Forward something useful",
  "Share food if you have extra",
  "Text a parent, sibling, or old friend one true line",
  "Stretch your neck",
  "Stretch your calves on a stair",
  "Stretch your hands",
  "Roll your shoulders back",
  "Stand up and reset the room",
  "Lie on the floor for two minutes",
  "Stand in the sun for two minutes",
  "Stand on one foot until you wobble",
  "Walk to the end of the block and back",
  "Take the stairs",
  "Walk one extra block",
  "Shake out your hands",
  "Touch your toes, or the honest attempt",
  "Twist until your back clicks",
  "Breathe out longer than you breathe in",
  "Take ten slow breaths",
  "Rest your eyes for sixty seconds",
  "Wash your face",
  "Wash your hands like you mean it",
  "Floss",
  "Brush your teeth even if it is not time",
  "Comb your hair",
  "Put on lotion",
  "Clip the nail that keeps catching",
  "Change into clothes that feel like you",
  "Take off the shoes",
  "Put on socks that are actually dry",
  "Crack the window and breathe",
  "Step outside",
  "Go outside barefoot if you can",
  "Sit on the stoop",
  "Look at the sky for a full minute",
  "Look for the moon",
  "Name five colors around you",
  "Name three sounds",
  "Feel the temperature on your skin",
  "Drink a second glass of water",
  "Fill a bottle and actually drink it",
  "Eat a piece of fruit",
  "Eat something with protein",
  "Eat without a screen",
  "Chew slowly for ten bites",
  "Make tea and sit with it",
  "Pour a glass of water for future you",
  "Eat lunch",
  "Have a snack before you get mean",
  "Stretch like a cat",
  "Roll your ankles",
  "Open your chest against a doorframe",
  "Hang your head and let your neck go",
  "Yawn on purpose",
  "Hum until your ribs buzz",
  "Sigh out loud",
  "Put a cold splash on your face",
  "Warm your hands on a mug",
  "Shake your whole body for twenty seconds",
  "Dance to one song",
  "Walk until the first corner that feels new",
  "Unclench your jaw",
  "Drop your tongue from the roof of your mouth",
  "Soften your eyes",
  "Put both feet on the floor",
  "Press your palms together hard, then let go",
  "Do ten slow squats",
  "Reach for the ceiling",
  "Twist at the waist and look behind you",
  "Clear the sink",
  "Wash the mug",
  "Wash two dishes you have been ignoring",
  "Empty the drying rack",
  "Wipe the table",
  "Wipe the bathroom mirror",
  "Wipe the phone screen",
  "Wipe the light switch",
  "Sweep one room",
  "Take out the trash",
  "Take out the recycling",
  "Break down a box",
  "Throw away the mystery leftovers",
  "Throw out the pens that do not work",
  "Make the bed",
  "Make the bed badly, but make it",
  "Change the pillowcase",
  "Put the clean clothes away",
  "Fold three things",
  "Start a load of laundry",
  "Move laundry from washer to dryer",
  "Hang the towel so it can dry",
  "Put the shoes by the door",
  "Put the scissors back",
  "Hang the coat",
  "Clear one chair",
  "Clear a square foot of desk",
  "Sort the junk drawer for four minutes",
  "Open the mail",
  "Recycle the junk mail",
  "File one paper",
  "Put keys where they belong",
  "Charge the thing that is always dead",
  "Unplug what does not need to be plugged in",
  "Turn off one light you do not need",
  "Open the blinds",
  "Close the blinds and make the room calm",
  "Water the plant",
  "Rotate the plant",
  "Pick the dead leaves off",
  "Wipe the stove",
  "Clean the cutting board",
  "Rinse the bottle",
  "Shake out the doormat",
  "Straighten the rug",
  "Fluff a pillow",
  "Put a glass of water by the bed",
  "Set out tomorrow's clothes",
  "Pack the bag tonight",
  "Empty your pockets",
  "Shake the crumbs from the keyboard",
  "Run a cloth over the door handle",
  "Put lids on things",
  "Freeze leftover bread",
  "Label the leftovers",
  "Check what you already have before wanting more",
  "Fold the grocery bags",
  "Open a window in the bathroom",
  "Knock the dust off a leaf",
  "Straighten the stack of books",
  "Coil the cable",
  "Find the flashlight",
  "Put a band-aid in your bag",
  "Wash the fruit",
  "Make the entryway passable",
  "Shake your jacket out",
  "Zip the bag so it is ready",
  "Put a pen where you always hunt for one",
  "Sharpen one pencil",
  "Recycle the cardboard",
  "Rinse the recycling so it is actually recyclable",
  "Put the wet umbrella where it can dry",
  "Look for a bird and watch it finish",
  "Learn the name of a tree outside",
  "Touch a leaf on purpose",
  "Smell the rain or the dry air",
  "Notice which way the wind is going",
  "Follow a bug with your eyes without killing it",
  "Pick up one piece of trash that is not yours",
  "Put trash in a bin, not near it",
  "Walk a loop around the building",
  "Sit under a tree",
  "Watch a cloud until it changes",
  "Find a flower, even a weed",
  "Listen for a bird you cannot see",
  "Feel the sun on the back of your hands",
  "Stand in shade for a minute",
  "Look at a far thing, then a close one",
  "Cross to the sunny side of the street",
  "Walk without headphones",
  "Trace a crack in the sidewalk",
  "Avoid stepping on the ant",
  "Say hello to a dog, then to the person",
  "Watch the sky change color",
  "Wait for the light without pulling the phone out",
  "Take the long way home by one street",
  "Sit on a bench you always pass",
  "Look into a shop window with no plan to buy",
  "Read a plaque",
  "Find a heart shape in the world",
  "Pick up a nice rock, then put it back",
  "Leave the pretty leaf where it is",
  "Point your face at the wind",
  "Let a bee have the flower",
  "Draw a terrible dog",
  "Draw the view from where you are",
  "Draw your own hand",
  "Doodle in the margin",
  "Write the ugly first draft",
  "Write one sentence",
  "Write three lines of anything",
  "Write a list of ten tiny wins",
  "Write tomorrow's first task on paper",
  "Write a poem that does not have to be good",
  "Write a joke",
  "Write the title of the thing",
  "Write a question you actually want answered",
  "Write down a dream before it fades",
  "Hum a melody you make up",
  "Sing badly on purpose",
  "Whistle",
  "Play a song you loved at sixteen",
  "Listen to one full song with no skip",
  "Listen to a song in a language you do not speak",
  "Drum on the table gently",
  "Clap a rhythm",
  "Invent a tiny dance",
  "Take a photo of light on a wall",
  "Take a photo of your own shadow",
  "Delete five screenshots",
  "Delete ten photos that are the same",
  "Make a folder and put three files in it",
  "Name a file so you can find it later",
  "Backup the file",
  "Save a copy",
  "Close the extra tabs",
  "Close the extra windows",
  "Unsubscribe from one email",
  "Unsubscribe from three",
  "Mute one group chat for a day",
  "Unfollow one account that makes you mean",
  "Turn off one notification",
  "Put the phone in another room for 20 minutes",
  "Turn the phone face down",
  "Charge the phone in another room overnight",
  "Change a password to a better one",
  "Clear five things from downloads",
  "Empty the computer trash",
  "Put one desktop file where it belongs",
  "Write the subject line first",
  "Archive the email you are done with",
  "Send the calendar invite",
  "Put the appointment on the calendar",
  "Set a timer for ten minutes and begin",
  "Set a timer for ten minutes and rest",
  "Delete the extra take and ship",
  "Confirm it in writing",
  "Make the reservation",
  "Book the appointment",
  "Cancel the thing you dread",
  "Pay the thing",
  "Check the balance",
  "Move a little money to savings",
  "Put a dollar in a jar",
  "Note what you spent today without judging it",
  "Check the weather so you can dress like a person",
  "Add the birthday to the calendar",
  "Renew the thing before it expires",
  "Fill out the form you have been avoiding",
  "Sign the paper",
  "Request the refund you are owed",
  "Check a tracking number, then stop checking",
  "Make the grocery list",
  "Check the pantry first",
  "Cook the simple thing",
  "Boil water",
  "Make toast",
  "Make eggs",
  "Cut an apple",
  "Wash a vegetable and eat it",
  "Cook rice",
  "Make a sandwich",
  "Assemble leftovers into a meal",
  "Add a vegetable to whatever you are eating",
  "Drink water before coffee",
  "Sit down to eat",
  "Set a place even if it is just you",
  "Use the nice plate",
  "Use the nice mug",
  "Make the coffee slowly",
  "Smell the spices",
  "Taste as you go",
  "Season it",
  "Let the tea steep the whole time",
  "Pack a snack for later",
  "Put fruit where you will see it",
  "Defrost what you will cook",
  "Soak the pan so future you does not hate you",
  "Wipe the counter while the water boils",
  "Put food on a plate instead of eating from the pan",
  "Eat the thing you have been saving for no reason",
  "Try the fruit you always skip",
  "Drink something warm",
  "Drink something cold on purpose",
  "Start it for ten minutes and stop if you want",
  "Do one item on the list, then stop",
  "Pick the cheaper option",
  "Pick the sooner date",
  "Leave 15 minutes earlier than you think",
  "Go to bed",
  "Set an alarm you will not hate",
  "Put the book on the pillow",
  "Fill the carafe now",
  "Write a sticky note for morning",
  "Put your bag by the door",
  "Check the locks",
  "Check that the stove is off",
  "Plug in the device you need tomorrow",
  "Put a glass of water in the fridge",
  "Find the other earring",
  "Find the other glove",
  "Put the library book in the bag",
  "Look up how long it actually takes to get there",
  "Leave a buffer",
  "Send the running-late text early enough",
  "Confirm the time",
  "Confirm the place",
  "Ask one person",
  "Ask the dumb question",
  "Read the instructions once",
  "Read them twice",
  "Save the draft",
  "Hit send",
  "Open the document",
  "Close the document and go outside",
  "Outline three bullets",
  "Delete a sentence that is showing off",
  "Read it out loud",
  "Fix one typo",
  "Fix the typo in the bio",
  "Put your name on the thing you made",
  "Credit someone",
  "Cite the source",
  "Bookmark something you will actually read",
  "Read one page",
  "Read one poem",
  "Read the next paragraph",
  "Read a page of something hard",
  "Read a page of something easy",
  "Look up a word",
  "Look up how to say it",
  "Learn one useful shortcut",
  "Learn the name of the thing on your desk",
  "Learn one fact about where you live",
  "Watch a short tutorial and pause to try it",
  "Practice the thing for five minutes",
  "Repeat the new word out loud",
  "Write one sentence in a language you are learning",
  "Review yesterday's note",
  "Copy a sentence you love by hand",
  "Memorize one line",
  "Explain the idea in one breath",
  "Draw a diagram that only you need",
  "Label the cables",
  "Google the error instead of staring",
  "Write down the error before it vanishes",
  "Try the simple fix first",
  "Restart the thing",
  "Sit still",
  "Do nothing for three minutes on purpose",
  "Stare at a wall",
  "Watch dust in a beam of light",
  "Take a bath or a long shower",
  "Let the water run over your hands",
  "Wrap yourself in a towel like a cape",
  "Put a blanket on",
  "Dim the lights",
  "Turn one lamp on",
  "Sit in the dark for a minute",
  "Listen to the room",
  "Put a hand on your chest and feel it move",
  "Count backwards from 40",
  "Name the feeling without fixing it",
  "Let yourself be bored",
  "Stop optimizing this hour",
  "Laugh at something tiny",
  "Smile at yourself in the mirror, unironically",
  "Make a dumb face",
  "Clap for yourself once, privately",
  "Say good job to yourself and do not undercut it",
  "Write a permission slip to rest",
  "Write a permission slip to begin",
  "Skip the thing that is only ego",
  "Stay home on purpose",
  "Go out on purpose",
  "Leave while you are still having an okay time",
  "Wear the loud thing",
  "Wear the quiet thing",
  "Take the compliment",
  "Do not argue with the compliment",
  "Replay a kind sentence",
  "Forget the unkind one on purpose",
  "Put the worry on paper",
  "Fold the worry paper and put it in a drawer",
  "Schedule the worry for later",
  "Do the next physical thing",
  "Water yourself like a plant",
  "Take the medication on time",
  "Book the dentist",
  "Book the thing you keep postponing",
  "Call instead of typing",
  "Leave a voicemail that is not a masterpiece",
  "Answer the phone",
  "Put the phone on do not disturb for one hour",
  "Tell someone you need five minutes",
  "Tell someone you need a day",
  "Ask for help on one specific thing",
  "Offer help on one specific thing",
  "Pay someone back",
  "Write down who you owe",
  "Keep a promise that is small",
  "Break a promise to a bad habit",
  "Do not buy it",
  "Put it back",
  "Wait 24 hours",
  "Wait ten minutes",
  "Sleep on it",
  "Decide",
  "Pick a direction and walk",
  "Turn left for a change",
  "Go around the block the other way",
  "Sit in a different chair",
  "Face the window",
  "Stand while you do the next three minutes",
  "Slow the next action by half",
  "Speed up the chore you hate so it ends",
  "Put on a timer and race the kitchen",
  "Make it a game",
  "Draw a star on the list",
  "Cross it off with a fat line",
  "Start a fresh page",
  "Do the easy one first",
  "Do the one you are avoiding for four minutes",
  "Open the bill",
  "Look at the number",
  "Make a plan for the number",
  "Save the PDF",
  "Make a folder",
  "Label the folder",
  "Date the note",
  "Write the recap in three bullets",
  "Send the recap",
  "Skip",
  "Hop",
  "Stretch your face",
  "Wiggle your toes",
  "Wiggle your fingers",
  "Make a shadow puppet",
  "Stack something carefully",
  "Shuffle cards if you have them",
  "Do one crossword clue",
  "Invent a riddle",
  "Make a pun and suffer it",
  "Tell a joke to the room",
  "Watch something that is only funny",
  "Watch something that is only beautiful",
  "Skip the news for one hour",
  "Skip the news for the rest of the day",
  "Look at art",
  "Look at one picture for a full minute",
  "Zoom in on a texture",
  "Look at the night sky, then look up from the phone",
  "Find a planet",
  "Find the big dipper or fail pleasantly",
  "Watch birds on a wire",
  "People-watch with kindness",
  "Invent a kind backstory for a stranger",
  "Wish a stranger well in your head",
  "Give up the better seat",
  "Stand so someone can sit",
  "Do not sigh in line",
  "Make small talk that is actually small",
  "Thank the driver",
  "Thank the cashier",
  "Thank the person on the phone",
  "Have the card ready",
  "Pack your bag before you get to the door",
  "Step aside",
  "Let people off first",
  "Lower your voice",
  "Lower the volume",
  "Take off headphones when someone talks to you",
  "Pause the podcast when you cross the street",
  "Look up from the phone in the crosswalk",
  "Look both ways",
  "Tie the shoe",
  "Double knot",
  "Wash the glasses",
  "Find the glasses",
  "Put chapstick in the pocket",
  "Reapply sunscreen if the sun is out",
  "Take off the wet socks",
  "Trim the hanging thread",
  "Safety-pin it for now",
  "Knock the mud off",
  "Wipe your feet",
  "Take the mat outside and shake it",
  "Change the air in the room",
  "Take the garbage out before it announces itself",
  "Open both ends of the house if you can",
  "Make a cross breeze",
  "Close the window when the rain comes",
  "Tighten the screw",
  "Oil the hinge",
  "Level the picture",
  "Hang the thing that has been leaning",
  "Take down the thing you do not like anymore",
  "Rearrange two objects",
  "Make a tiny altar of three nice things",
  "Put flowers in a jar, even weeds",
  "Put herbs in a glass of water",
  "Plant a seed",
  "Name the plant",
  "Talk to the plant",
  "Move the plant to better light",
  "Wipe the dust off the leaves",
  "Catch the spider and put it outside",
  "Fill a saucer of water for bees",
  "Put out seed if you have it",
  "Watch the squirrel steal it and allow it",
  "Wave thanks",
  "Wave sorry",
  "Let the merge happen",
  "Close the door softly",
  "Turn down the argument",
  "Do not post it",
  "Draft it, then delete it",
  "Wait until morning to reply",
  "Reply kindly to a mistake",
  "Send the heart",
  "React so they know you saw it",
  "Leave a comment that adds one true thing",
  "Do not pile on",
  "Ask a follow-up",
  "Write the name down",
  "Spell it right",
  "Ask how to pronounce it",
  "Use their name",
  "Speak up once",
  "Let someone else speak",
  "Credit the idea",
  "Pass the mic",
  "Read to someone",
  "Read to yourself out loud",
  "Record a voice memo of the idea",
  "Title the memo",
  "Make a checklist of three",
  "Check one off",
  "Start the kettle",
  "Sit while it boils",
  "Come back when it sings",
  "Pour slowly",
  "Hold the warm thing",
  "Look out the window while it cools",
  "Take the first sip like it matters",
  "Whisper the thing you cannot scream",
  "Write the thing you cannot say",
  "Practice the hard sentence",
  "Practice the kind sentence",
  "Practice your name like you like it",
  "Sign your name slowly",
  "Draw a sun",
  "Map the day in three boxes",
  "Put a verb on a sticky note",
  "Put the sticky note on the door",
  "Do the verb",
  "Cross the verb out",
  "Write the next verb",
  "Rest between verbs",
  "Put music on for the next verb",
  "Put silence on for the next verb",
  "Open the curtains",
  "Close the laptop",
  "Push the chair in",
  "Leave the room and come back",
  "Walk to another room with no phone",
  "Fetch a glass of water",
  "Look at a photo of someone you love",
  "Look at a photo of a place you love",
  "Look at a photo of yourself as a kid and be decent to them",
  "Write that kid a line",
  "Write future you a line",
  "Set a reminder that is kind",
  "Set a reminder that is useful",
  "Delete reminders you will ignore",
  "Stretch your hip",
  "Stretch your wrist",
  "Look twenty feet away for twenty seconds",
  "Blink ten times",
  "Close your eyes and listen",
  "Cover your eyes with your palms",
  "Press your fingers along your brow",
  "Rub your temples",
  "Rub your hands together until they are warm",
  "Place the warm hands on your eyes",
  "Nod yes",
  "Shake your head no, then decide",
  "Choose",
  "Stick with the first choice for an hour",
  "Write why",
  "Write why not",
  "Tear up why not",
  "Keep why",
  "Put it on the fridge",
  "Live it for ten minutes",
  "Stop at a good enough version",
  "Ship the draft",
  "Send the file",
  "Check the attachment",
  "Check the address",
  "Be on time",
  "Be early",
  "Be present",
  "Put the laptop away at the table",
  "Put the phone in a bowl",
  "Leave it there",
  "Ask what the best part was",
  "Ask what the hard part was",
  "Do not fix it unless they ask",
  "Bring water",
  "Bring a snack",
  "Show up",
  "Stay to the end of the song",
  "End the call kindly",
  "Say goodbye like you mean it",
  "Wave from the door",
  "Lock up",
  "Read in bed",
  "Stop reading at a good sentence",
  "Lie on your back",
  "Put the pillow how you like it",
  "Cool the room a little",
  "Warm the room a little",
  "Crack one window",
  "No screen for ten minutes before sleep",
  "Ten minutes of nothing",
  "Think of three rooms you have loved",
  "Think of three people who are fine",
  "If you cannot sleep, get up and fold one shirt",
  "If you cannot sleep, write the loop down",
  "Then try again",
  "Be patient with the night",
  "Be patient with the morning",
  "Get up when you can, without the speech",
  "Put your feet on the floor",
  "Stand",
  "Open the day with a window",
  "Do not open the feed first",
  "Eat something",
  "Then begin",
  "Put both hands on the work",
  "Then take them off and rest",
  "Then put them back",
  "Write a thank you to the day",
  "Feed yourself like someone you love",
  "Pay attention for one full minute",
  "Notice something beautiful that is also ordinary",
  "Point it out",
  "Keep it to yourself and smile",
  "Take the long exhale",
  "Take the compliment home",
  "Take a joke well",
  "Take a break",
  "Take a walk around the furniture",
  "Take your time",
  "Give it space",
  "Give it a name",
  "Give someone the last word",
  "Give yourself the last word, kindly",
  "Keep your word",
  "Keep the drawing",
  "Keep the plant alive one more week",
  "Keep the peace in the room you are in",
  "Keep your keys in one place",
  "Keep going for one more minute",
  "Stop",
  "Start",
  "Begin in the middle",
  "Finish the last inch",
  "Leave it unfinished so tomorrow is easy",
  "Leave a note",
  "Leave it better than you found it",
  "Leave the argument",
  "Leave room for someone else",
  "Leave on time",
  "Do the dishes so morning is kind",
  "Or leave the dishes if that is how you last",
  "Pick the kind version of the next hour",
  "Pick the brave version of the next five minutes",
  "Pick the rest version if you need it",
  "Pick one thing and do it",
  "Do this, then stop",
  "Go be a person in the world for a bit",
  "Salt something that needs salt",
  "Sit up straight for one full song",
  "Do a wall sit until you want to quit, then five more seconds",
  "Vacuum the obvious path",
  "Refill the soap",
  "Restock the toilet paper",
  "Test the smoke alarm",
  "Refill the water filter",
  "Clear the fridge door",
  "Put a photo where you will see it",
  "Replace the burned-out bulb if you have one",
  "Count the windows you can see",
  "Watch steam or breath in the air",
  "Collect one nice rock and keep it",
  "Listen to the HVAC, the traffic, the quiet",
  "Notice a smell you like and stay with it",
  "Take a photo of your lunch like you mean it",
  "Log out of the thing you open on reflex",
  "Update the app that keeps nagging",
  "Pin the document you always hunt for",
  "Star the email you will actually answer",
  "Print the ticket or save it offline",
  "Order the refill",
  "Preheat the oven with a plan",
  "Stir the pot",
  "Stop eating when you are not hungry, once",
  "Share a recipe you actually use",
  "Look up what is in season",
  "Add lemon if you have it",
  "Make ice",
  "Lay out the medication you already take",
  "Iron or smooth one shirt",
  "Pick tomorrow's socks",
  "Charge the transit card or check the ticket",
  "Screenshot the address",
  "Write the address on paper",
  "Measure twice",
  "Hit save",
  "Cut the first paragraph",
  "Update the year on the thing",
  "Read a page of the book you are pretending to read",
  "Count to twenty in another language",
  "Highlight one line worth keeping",
  "Recite something you have memorized",
  "Read the label",
  "Sit in the shower",
  "Take a blanket off",
  "Sit in a different patch of light",
  "Work from a different corner",
  "Face the door",
  "Sit to do the thing you always rush",
  "Keep score of tiny wins",
  "Give yourself a point",
  "Number a list of five",
  "Do number one",
  "Ask about a payment plan",
  "Read one clause",
  "Scan the receipt",
  "Photograph the whiteboard, then erase it",
  "Write the agenda",
  "Play one hand of something simple",
  "Do a single sudoku cell",
  "Solve one riddle",
  "Listen to a comedy clip",
  "Look at old maps",
  "Watch the ISS if it is passing",
  "Offer your spot in line if they have two items",
  "Comment on the good mural",
  "Thank the bus driver",
  "Be easy to help",
  "Walk on the right",
  "Keep your bag on your lap",
  "Lower the brightness",
  "Put on headphones for the loud world",
  "Wear the lights if you bike at night",
  "Pull up the sock",
  "Button the thing that is flapping",
  "Case the sunglasses",
  "Put a tissue in the pocket",
  "Put on a hat",
  "Dry your feet",
  "Sew the button if you can",
  "Polish the shoe with the other shoe",
  "Beat a pillow",
  "Boil vinegar if the kitchen smells like yesterday",
  "Sprinkle baking soda in the bin",
  "Listen to the breeze",
  "Put a pot under the leak",
  "Report the leak",
  "Photograph the damage",
  "Tape the tear",
  "Glue the tiny thing",
  "Stick a felt pad under the chair",
  "Grow the avocado pit or laugh at it",
  "Plant nothing, just prepare a pot",
  "Mix the soil with your hands",
  "Wash the dirt off and notice it",
  "Apologize to the plant",
  "Let the spider live in the corner if that is the deal",
  "Clean a bird feeder",
  "Do not honk",
  "Slow down at the yellow",
  "Stop fully",
  "Leave the group chat drama",
  "Assume the missing comma was not an attack",
  "Use a period, not a dagger",
  "Send the uncool emoji",
  "Change the topic to something living",
  "Remember the name of the pet they mentioned",
  "Use your own name when you order",
  "Ask the quietest person what they think",
  "Answer a child honestly",
  "Transcribe one sentence of the voice memo",
  "Put it where the project lives",
  "Do not watch the kettle",
  "Stretch after the tea",
  "Practice the sentence you owe someone",
  "Doodle a house",
  "Morning, afternoon, night: one verb each",
  "Celebrate a verb with a stretch",
  "Push the chair back and stand",
  "Fetch a sweater",
  "Fetch nothing and come back anyway",
  "Keep one reminder",
  "Do that one",
  "Stretch your thumb",
  "Shake the mouse hand out",
  "Rub your feet",
  "Place warm hands on your neck",
  "Choose again",
  "Rechoose after an hour if you must",
  "Tape the why to the wall",
  "Live it for the next task",
  "Attach the right file",
  "Check the time zone",
  "Fix it if they ask",
  "Bring a sweater",
  "Bring yourself",
  "Stay to the end of the meeting",
  "Leave when you said you would",
  "Watch them go, then go in",
  "Lights out",
  "One lamp left on",
  "Turn the page down",
  "Lie on your side",
  "Extra blanket or none",
  "Earplugs or the fan",
  "Think of water",
  "Think of nothing",
  "If you cannot sleep, drink water",
  "Get up when you said",
  "Make the first decision: water",
  "That is plenty",
  "Feed someone",
  "Take the leftovers",
  "Give it time",
  "Give it a rest",
  "Keep a spare",
  "Keep Friday night empty",
  "Keep a promise to walk",
  "Begin",
  "Leave a light",
  "Leave a tip",
  "Leave room for dessert",
  "Leave the office on time",
  "Scream into a pillow",
  "Write a thank you on paper, not just in your head",
  "Feed the birds your extra oats",
  "Open the door and yell a kind word at the sky",
  "Put your phone on the table and talk",
  "Make the bed with hospital corners or none, just finish",
  "Rinse your mouth",
  "Wash the fruit bowl",
  "Put a chair in the sun and sit in it",
  "Name one thing you can finish before dark",
  "Put the clean dish away, not next to the sink",
  "Take the long way to the mailbox",
  "Write the first ugly sentence",
  "Let someone merge",
  "Water the plant even if it looks fine",
  "Stand in a doorway and drop your arms",
  "Put the scissors in the same place twice",
  "Listen to the ice in the glass",
  "Say the compliment out loud",
  "Fix the snag in the sweater",
  "Put a coin in the tip jar",
  "Read the last paragraph of a book you loved",
  "Walk until your shoulders drop",
  "Throw away one expired thing",
  "Put a bowl of water on the step",
  "Draw the same cup three times",
  "Turn your ring, watch, or bracelet and start the hour over",
  "Call the friend whose name popped up today",
  "Sit on the floor and sort one pile",
  "Make a sandwich for someone else too",
  "Look at the ceiling and count the cracks like stars",
  "Put the wet sponge where it can dry",
  "Write five words that are true",
  "Take the recycling even if it is not full",
  "Hum the next task",
  "Leave a glass of water in every room you work in",
  "Clap dust out of a cloth",
  "Tell the void you are trying",
  "Put your name on the list",
  "Go outside and come back colder or warmer on purpose",
  "Fold the top blanket",
  "Save the last good bite for yourself",
  "Wave at a passing bus like you know it",
  "Write the check or tap the pay button",
  "Stretch in the kitchen while the microwave runs",
  "Put the lid on the marker",
  "Look up a bird you saw and did not know",
  "Give the extra sticker to a kid",
  "Take one book off the to-read pile and open it",
  "Wipe the handle of the fridge",
  "Say goodnight to the room",
  "Put both hands on a tree for ten seconds",
  "Do the smallest repair",
  "Leave a cup of sugar for a neighbor if they asked",
  "Turn the page of the calendar",
  "Breathe in the spice cabinet",
  "Write luck a list of what already worked",
  "Put your shoes on and stand at the door, then decide",
  "Fill the birdbath or the bowl",
  "Write thank you on the receipt",
  "Step into the weather for sixty seconds",
  "Clear the notifications that are not people",
  "Make a tiny bouquet from weeds",
  "Tell someone they made the day easier",
  "Rest like it is part of the work",
  "Go be useful to the next five minutes",
  "Write a thank-you on a sticky note and put it on a laptop",
  "Feed a stray cat if one is around, or leave water",
  "Open the oldest unread and answer it or archive it",
  "Put a stamp on the letter you keep meaning to send",
  "Walk to a window you never use and look out",
  "Put a plant in the path of your day",
  "Name one fear and then do a tiny unrelated kindness",
  "Turn the socks right-side out",
  "Make a playlist of eight songs and play it once",
  "Wipe the screen you keep squinting at",
  "Leave a good comment on a small thing",
  "Stand in line without buying a story about it",
  "Put ice on the back of your neck",
  "Write the first line of a letter to someone dead or far",
  "Sweep the stoop",
  "Give the extra banana away",
  "Sit with a cold glass and no phone",
  "Stretch until you yawn",
  "Put the library hold on the book",
  "Say thank you to the room that holds you",
];
