export const SEER_LINES = [
  "Arguing with a fool only proves there are two.",
  "Not every invitation deserves an RSVP.",
  "Peace is often worth more than being right.",
  "You do not have to attend every argument you are invited to.",
  "A closed mouth rarely has to explain itself.",
  "Listen twice as much as you speak.",
  "What people do matters more than what they promise.",
  "Silence can answer questions words cannot.",
  "Never make permanent decisions from temporary emotions.",
  "If you have to force it, it probably does not fit.",
  "A bad day is not a bad life.",
  "Your first reaction does not have to become your response.",
  "Being misunderstood is sometimes the price of having boundaries.",
  "You cannot control the wind, only your sails.",
  "What you tolerate teaches people how to treat you.",
  "Sometimes walking away is winning.",
  "Do not trade your peace for someone else's approval.",
  "Your attention is more valuable than you think.",
  "Being busy and moving forward are not the same thing.",
  "You cannot heal in the same habits that hurt you.",
  "A lesson repeated is usually a lesson ignored.",
  "The truth does not become false because someone dislikes it.",
  "Do not explain yourself to people committed to misunderstanding you.",
  "Know when enough is enough.",
  "You are allowed to change your mind when you learn more.",
  "Pride is expensive.",
  "A calm answer is stronger than a loud reaction.",
  "When someone shows you a pattern, believe the pattern.",
  "Your reputation is built when nobody is applauding.",
  "Do not borrow trouble from tomorrow.",
  "Sometimes the best response is no response.",
  "You can forgive without reopening the door.",
  "Do not confuse familiarity with safety.",
  "Time reveals what words conceal.",
  "Choose people who choose you.",
  "A boundary without consequences is only a suggestion.",
  "Do not let loneliness negotiate your standards.",
  "If it costs your self-respect, it is too expensive.",
  "A clear conscience sleeps better than an impressive reputation.",
  "The loudest person is rarely the wisest.",
  "You cannot pour from an empty cup.",
  "Rest is maintenance, not failure.",
  "Do not mistake chemistry for compatibility.",
  "The right path is not always the easiest one.",
  "People reveal themselves through repetition.",
  "Be careful who gets access to you.",
  "Your future needs you more than your past does.",
  "Small choices become large consequences.",
  "The longer you avoid a problem, the more rent it charges.",
  "Never underestimate the power of simply leaving.",
  "If someone wants to misunderstand you, more words rarely help.",
  "Sometimes closure is realizing you deserved better.",
  "Protect your peace before you have to rebuild it.",
  "Confidence does not need an audience.",
  "Do not mistake someone's potential for their character.",
  "The apology matters less than the changed behavior.",
  "You can love someone and still leave them behind.",
  "Not everyone deserves the full story.",
  "Your boundaries will disappoint people who benefited from you having none.",
  "A little patience prevents a lot of regret.",
  "Nothing changes if nothing changes.",
  "You cannot save people from lessons they insist on learning.",
  "Be slow to trust and quick to notice patterns.",
  "Never let urgency bully you into stupidity.",
  "Good intentions do not erase bad consequences.",
  "The right answer sometimes arrives after the emotion leaves.",
  "You do not need permission to protect yourself.",
  "Being kind does not require being naive.",
  "You can be compassionate without being available.",
  "If they only respect your boundary after you explode, they never respected it.",
  "Every reaction trains the people around you.",
  "Do not fight battles that have no prize.",
  "When respect leaves, distance should follow.",
  "Some people deserve forgiveness from afar.",
  "Familiar pain is still pain.",
  "Do not confuse being needed with being valued.",
  "Your worth does not rise and fall with someone's opinion.",
  "Let people underestimate you.",
  "Protect your time like money.",
  "Do not spend tomorrow's energy on today's anger.",
  "There is strength in not needing the last word.",
  "A peaceful life often requires disappointing people.",
  "You cannot argue someone into emotional maturity.",
  "Sometimes the lesson is simply not to go back.",
  "Trust takes years and seconds to destroy.",
  "Do not make excuses for patterns that hurt you.",
  "Your peace is a valid reason.",
  "People who respect you do not require constant reminders.",
  "You are responsible for your actions, not everyone's reaction.",
  "Be careful what you normalize.",
  "Never chase someone who enjoys watching you run.",
  "A sincere no is kinder than a resentful yes.",
  "Your habits are voting for your future.",
  "Some doors close because you finally stopped holding them open.",
  "A mistake becomes wisdom when you stop repeating it.",
  "You do not have to prove what you already know.",
  "Keep your standards higher than your desperation.",
  "Nothing good comes from arguing with someone who enjoys conflict.",
  "Sometimes maturity looks boring from the outside.",
  "Your life gets lighter when you stop carrying everyone else's opinion.",
  "Do not let one bad chapter convince you the story is over.",
  "Being alone is better than being poorly accompanied.",
  "The strongest boundaries are quietly enforced.",
  "You can miss someone without needing them back.",
  "If respect has to be begged for, it is already gone.",
  "Not everyone who loses you deserves another chance.",
  "Make decisions your future self will thank you for.",
  "Do not answer disrespect with self-destruction.",
  "Know the difference between patience and wasting time.",
  "What is meant for you should not require abandoning yourself.",
  "Keep promises to yourself.",
  "Your environment shapes you more than motivation does.",
  "The people around you become part of your inner voice.",
  "Pay attention to how you feel after spending time with someone.",
  "Being liked is not the same as being respected.",
  "Do not shrink yourself to make someone comfortable.",
  "Say less. Notice more.",
  "The truth usually needs fewer words.",
  "Your nervous system knows things your ego argues with.",
  "When something feels wrong repeatedly, stop calling it coincidence.",
  "Calm is a competitive advantage.",
  "Discipline carries you when motivation disappears.",
  "Make the hard choice while it is still easy.",
  "The smallest leak can sink the biggest ship.",
  "Your weakest habit can undo your strongest intention.",
  "Do not confuse motion with progress.",
  "Start before you feel ready.",
  "Perfect is often procrastination wearing nice clothes.",
  "You cannot improve what you refuse to face.",
  "Consistency beats intensity.",
  "Ten minutes every day beats two hours once a month.",
  "Finish more things than you announce.",
  "Let your work speak before you do.",
  "If it matters, schedule it.",
  "Motivation gets you started; systems keep you going.",
  "Your calendar reveals your priorities.",
  "Your spending reveals them too.",
  "Make fewer promises and keep more of them.",
  "The easiest way to earn trust is to be dependable.",
  "Do not confuse talent with preparation.",
  "Slow progress is still progress.",
  "A shortcut often sends you somewhere else.",
  "The boring basics usually work.",
  "Stop restarting and start continuing.",
  "One imperfect step beats ten perfect plans.",
  "Momentum is easier to maintain than rebuild.",
  "A little discipline saves a lot of regret.",
  "Do tomorrow a favor tonight.",
  "A clean start often begins with a clean space.",
  "If you cannot do everything, do something.",
  "You do not need a new life; sometimes you need a new routine.",
  "The things you repeat become the person you are.",
  "Build habits that work on bad days.",
  "Make important things easy to start.",
  "Remove friction from good habits.",
  "Add friction to bad ones.",
  "Your future is hiding inside ordinary Tuesdays.",
  "Nobody sees most of the work that changes your life.",
  "Success usually looks boring before it looks impressive.",
  "The first hour of your day can shape the next fifteen.",
  "Protect your mornings from unnecessary chaos.",
  "Go to bed before your problems start sounding philosophical.",
  "Exhaustion makes bad ideas sound reasonable.",
  "Hungry, angry, lonely, and tired are terrible advisers.",
  "Take care of your body before asking your mind to perform miracles.",
  "Water fixes more problems than people give it credit for.",
  "Sleep before sending the message.",
  "Eat before deciding everyone hates you.",
  "Walk before declaring the day ruined.",
  "A shower can sometimes reset more than your body.",
  "Change your surroundings when your thoughts get stuck.",
  "Do not solve imaginary problems at 2 a.m.",
  "Tomorrow's version of you may see it differently.",
  "Give decisions enough time to become decisions instead of reactions.",
  "Most catastrophes feel smaller after sleep.",
  "Take the next reasonable step.",
  "You do not need the entire staircase.",
  "Progress loves specificity.",
  "Vague goals create vague results.",
  "Write it down before trusting your memory.",
  "Your brain is for thinking, not storing reminders.",
  "Make lists before your mind makes panic.",
  "Do the task that future-you keeps begging you to do.",
  "Five minutes of effort can break an hour of dread.",
  "Starting is often harder than doing.",
  "Do difficult things before your excuses wake up.",
  "Prepare when nobody is watching.",
  "Luck favors people already in motion.",
  "Opportunities are easier to notice when you are prepared.",
  "Make yourself easy to recommend.",
  "Being reliable is an underrated superpower.",
  "Show up when you say you will.",
  "Answer the message.",
  "Return what you borrow.",
  "Admit when you do not know.",
  "Ask before assuming.",
  "Check before accusing.",
  "Read before reacting.",
  "Think before posting.",
  "Sleep before quitting.",
  "Money cannot buy happiness, but chaos charges interest.",
  "Spend less than you earn whenever possible.",
  "A sale is not savings if you did not need it.",
  "Cheap becomes expensive when you buy it twice.",
  "Do not spend money to impress people who are not paying your bills.",
  "Emergency funds buy peace before they buy anything else.",
  "Your lifestyle can rise faster than your income.",
  "Wanting it is not the same as affording it.",
  "The best purchase is sometimes the one you skip.",
  "Convenience has a price. Know when it is worth paying.",
  "Time is a currency too.",
  "Spend money to save time when the trade actually improves your life.",
  "Do not let small subscriptions become invisible rent.",
  "Read the fine print when money is involved.",
  "Never lend what you cannot afford to lose.",
  "If someone pressures you financially, slow down.",
  "Urgency is a favorite tool of scammers and manipulators.",
  "When a deal feels too good, investigate the feeling.",
  "Financial freedom is built quietly.",
  "Wealth and looking wealthy are often opposites.",
  "Take care of what you already own.",
  "Maintenance is cheaper than replacement.",
  "Organize before buying more storage.",
  "Use what you have before buying what you imagine you need.",
  "Clutter is delayed decision-making.",
  "Everything you own owns a little piece of your attention.",
  "Buy fewer things you actually like.",
  "Quality matters most on things you use every day.",
  "Experiences become memories; clutter becomes chores.",
  "Your house should serve your life, not impress strangers.",
  "Clean as you go when possible.",
  "Put things where you naturally reach for them.",
  "Organization should reduce effort, not create rituals.",
  "If a system is too complicated to maintain, simplify it.",
  "Make the right thing the easy thing.",
  "Put your keys in the same place.",
  "Charge your phone before you need it.",
  "Leave earlier than you think you need to.",
  "Five minutes early feels better than fifteen minutes late.",
  "Preparation is cheaper than panic.",
  "Pack the night before.",
  "Keep backups of things that would ruin your week if lost.",
  "Passwords deserve better than your pet's name.",
  "Back up your photos.",
  "Save important documents somewhere boring and reliable.",
  "Check the weather before blaming the universe.",
  "Read directions before assembling confidence.",
  "Measure twice, cut once.",
  "Test before committing.",
  "Keep receipts until you know the thing works.",
  "Never mistake confidence for competence.",
  "Smart people can still make dumb decisions.",
  "Intelligence without humility becomes a liability.",
  "The more certain you feel, the more useful a second look may be.",
  "Question your assumptions before defending them.",
  "Changing your opinion is evidence you learned something.",
  "Being wrong quickly is better than being wrong stubbornly.",
  "Curiosity ages better than certainty.",
  "Ask better questions.",
  "A question can save an hour of guessing.",
  "Do not pretend to understand what you could simply ask about.",
  "Learn from people you disagree with.",
  "You do not have to adopt an idea to understand it.",
  "Two things can be true at once.",
  "Context changes meaning.",
  "Exceptions do not erase patterns.",
  "Patterns do not guarantee exceptions.",
  "Anecdotes are not evidence.",
  "Confidence is not proof.",
  "Popularity is not truth.",
  "Tradition is not automatically wisdom.",
  "New is not automatically better.",
  "Old is not automatically outdated.",
  "Ask what problem something is actually solving.",
  "Complexity should earn its place.",
  "Simple is difficult and usually worth it.",
  "Explain it simply to see if you understand it.",
  "Learn the rules before deciding which ones to break.",
  "Experts still check their work.",
  "Memory is confident even when it is wrong.",
  "Write things down.",
  "Verify important details.",
  "Screenshots save arguments.",
  "Dates matter.",
  "Names matter.",
  "Details matter most when everyone assumes they do not.",
  "Do not trust autocorrect with relationships.",
  "Reread before sending.",
  "Tone disappears in text.",
  "If nuance matters, call.",
  "If emotions are high, wait.",
  "If documentation matters, write.",
  "If safety matters, verify.",
  "If money matters, read.",
  "If trust matters, communicate.",
  "If love matters, show it.",
  "If it hurts, address it.",
  "If it works, maintain it.",
  "If it fails repeatedly, redesign it.",
  "Learn the lesson before changing the scenery.",
  "Friendship should not feel like an audition.",
  "Notice who celebrates your good news.",
  "Notice who only calls when they need something.",
  "Good friends can tell you uncomfortable truths.",
  "Loyalty without honesty becomes enabling.",
  "Do not demand loyalty to behavior you know is wrong.",
  "People can love you and still be bad for you.",
  "History is not an obligation.",
  "Length of friendship does not guarantee quality.",
  "Shared memories are not a reason to share your future.",
  "Some friendships expire without anyone being evil.",
  "Outgrowing someone is not betrayal.",
  "You do not need drama to justify distance.",
  "A healthy relationship survives boundaries.",
  "Respect should survive disagreement.",
  "Love does not require constant access.",
  "You can care deeply and still say no.",
  "Someone else's disappointment does not automatically mean you did something wrong.",
  "Do not confuse guilt with responsibility.",
  "Do not confuse sympathy with obligation.",
  "Help people without becoming their life-support system.",
  "Rescue creates resentment when it becomes expected.",
  "You cannot carry someone who refuses to walk.",
  "Support does not mean doing everything for them.",
  "Sometimes helping means letting consequences arrive.",
  "Kindness without boundaries becomes self-neglect.",
  "Your generosity needs a budget.",
  "Give because you want to, not because you fear saying no.",
  "Resentment often points toward a boundary you failed to set.",
  "Speak before resentment becomes cruelty.",
  "Difficult conversations are cheaper when held early.",
  "Say the uncomfortable thing kindly.",
  "Be clear enough that resentment cannot hide in ambiguity.",
  "Hinting is not communication.",
  "Expectations nobody knows about are future disappointments.",
  "Ask for what you need.",
  "Accept that the answer may be no.",
  "Respect other people's no if you want yours respected.",
  "Consent is not enthusiasm's quiet cousin; it should actually be clear.",
  "Do not punish honesty after asking for it.",
  "Make it safe for people to tell you the truth.",
  "Do not ask questions when you only accept one answer.",
  "Listen for understanding instead of ammunition.",
  "Disagreement is not automatically disrespect.",
  "Criticism is not always rejection.",
  "Feedback is information, not a verdict.",
  "A defensive reaction can hide a useful truth.",
  "You can dislike how something was said and still learn from it.",
  "Not every criticism deserves acceptance.",
  "Consider the source without ignoring the message.",
  "Do not argue facts with feelings or feelings with facts.",
  "Validate emotion without inventing agreement.",
  "You can understand someone without excusing them.",
  "Empathy does not require surrendering judgment.",
  "Compassion and consequences can coexist.",
  "Forgiveness and trust are separate decisions.",
  "Trust should be rebuilt with evidence.",
  "An apology begins the repair; it does not complete it.",
  "Changed behavior is the loudest apology.",
  "Repeated apologies without change become manipulation.",
  "Believe effort, not speeches.",
  "Watch what happens after the conversation.",
  "Healthy people adjust.",
  "People who care about the relationship care about the repair.",
  "Do not chase clarity from someone creating confusion.",
  "Mixed signals are still information.",
  "Inconsistent affection is not stability.",
  "Attention is not commitment.",
  "Attraction is not alignment.",
  "Love cannot compensate for incompatibility forever.",
  "Shared values matter when excitement fades.",
  "Choose someone you can solve problems with.",
  "Watch how people handle disappointment.",
  "Watch how they treat people they do not need.",
  "Watch how they behave when nobody is impressed.",
  "Character appears when convenience disappears.",
  "Respect shows up most clearly during conflict.",
  "Cruelty during anger is still cruelty.",
  "Anger explains behavior; it does not excuse everything.",
  "You cannot unhear certain words.",
  "Fight the problem, not each other.",
  "Do not use someone's vulnerability as ammunition later.",
  "Secrets shared in trust should remain protected after a friendship ends.",
  "Integrity matters after the relationship does.",
  "Leave people with dignity when possible.",
  "You can end something without destroying it.",
  "Closure does not require revenge.",
  "Winning the breakup is not a real prize.",
  "Revenge keeps people connected longer than love sometimes does.",
  "Indifference is often cleaner than retaliation.",
  "Stop checking doors you already closed.",
  "Nostalgia edits out the bad parts.",
  "Missing the good does not erase the reason you left.",
  "Loneliness can romanticize terrible situations.",
  "Do not text the past because the present feels quiet.",
  "Quiet is not empty.",
  "Learn to enjoy your own company.",
  "Solitude becomes powerful when it is chosen well.",
  "Build a life you do not constantly need to escape.",
  "Your relationships should add life, not replace it.",
  "Do not apologize for taking up reasonable space.",
  "Confidence is built by surviving things, not imagining you could.",
  "Courage usually feels like fear with forward motion.",
  "You can be scared and still do it.",
  "Waiting for fear to disappear wastes time.",
  "The first attempt is allowed to be ugly.",
  "Beginners are supposed to look like beginners.",
  "Embarrassment is tuition.",
  "Failure teaches lessons success can hide.",
  "Losing is information.",
  "Rejection redirects more lives than acceptance does.",
  "A no saves time.",
  "Ask anyway.",
  "The worst realistic outcome is often survivable.",
  "Most people are thinking about themselves, not judging you.",
  "Nobody remembers your awkward moment as long as you do.",
  "Confidence grows after action, not before it.",
  "Practice makes courage less dramatic.",
  "Do the thing badly before demanding you do it brilliantly.",
  "Skills are built, not discovered.",
  "Talent is useful; persistence is dangerous.",
  "Do not quit because somebody else started earlier.",
  "Comparison ignores context.",
  "You are seeing their highlight and your behind-the-scenes.",
  "Their success does not take yours away.",
  "Envy can reveal what you want.",
  "Turn jealousy into information.",
  "Admire without diminishing yourself.",
  "Learn without copying someone's entire life.",
  "The goal is not to become them.",
  "Be inspired, then become more yourself.",
  "You do not need universal approval to be successful.",
  "Every worthwhile choice disappoints some imagined audience.",
  "Stop performing for people who are not watching.",
  "Do not build a life around proving somebody wrong.",
  "Build one you enjoy even if they never notice.",
  "Spite is excellent ignition and terrible fuel.",
  "Let anger start the engine, not steer the car.",
  "Discipline should eventually replace revenge.",
  "Your goals deserve healthier motivation than hatred.",
  "Do it because it improves your life.",
  "A win nobody sees still counts.",
  "Private progress is still progress.",
  "You do not need to announce every transformation.",
  "Move quietly when noise creates pressure.",
  "Tell fewer people what you are about to do.",
  "Let completion make the announcement.",
  "Protect new plans while they are fragile.",
  "Seeds grow underground before anyone sees anything.",
  "Not all progress is visible.",
  "Healing sometimes looks like being bored by things that once consumed you.",
  "Growth can feel like losing interest.",
  "Peace can feel unfamiliar after chaos.",
  "Do not mistake calm for emptiness.",
  "Stability may feel boring when you are used to emergencies.",
  "Give healthy things time to feel normal.",
  "Your body can crave patterns your mind knows are harmful.",
  "Familiarity is powerful, not necessarily trustworthy.",
  "Break cycles before they become traditions.",
  "What you refuse to heal can become someone else's burden.",
  "You cannot change the beginning.",
  "You can change what the beginning becomes.",
  "Your past explains you; it does not own you.",
  "You are not required to repeat your history.",
  "Learning the reason for a behavior does not mean keeping it.",
  "Self-awareness without change is sophisticated repetition.",
  "Knowing better only matters when you eventually do better.",
  "Progress includes catching yourself sooner.",
  "A smaller mistake is still improvement.",
  "Fewer bad days is progress.",
  "Recovering faster is progress.",
  "Asking for help sooner is progress.",
  "Saying no sooner is progress.",
  "Leaving sooner is progress.",
  "Apologizing sooner is progress.",
  "Starting again sooner is progress.",
  "Growth is often measured in recovery time.",
  "You do not have to become perfect to become better.",
  "Aim for better patterns, not a flawless personality.",
  "Nobody graduates from being human.",
  "Self-respect is built through decisions.",
  "Every boundary is a vote for self-respect.",
  "Every kept promise to yourself matters.",
  "Do not repeatedly abandon yourself to keep others comfortable.",
  "You deserve your own loyalty too.",
  "Treat yourself like someone whose future matters.",
  "Speak to yourself in ways that actually improve performance.",
  "Cruelty toward yourself is not discipline.",
  "Shame rarely builds anything sturdy.",
  "Accountability works better when paired with possibility.",
  "Admit the mistake without becoming the mistake.",
  "Regret is useful only if it changes your next move.",
  "Guilt should point somewhere constructive.",
  "Make amends where possible.",
  "Then stop using remorse as self-punishment.",
  "You cannot repair yesterday by ruining today.",
  "Learn, repair, continue.",
  "The best apology to your past is a better future.",
  "Start from where you are, not where you wish you had started.",
  "Halfway late is still earlier than never.",
  "Time passes whether you begin or not.",
  "A year from now will arrive anyway.",
  "Plant the tree.",
  "Take the class.",
  "Make the call.",
  "Submit the application.",
  "Start the project.",
  "Clean the room.",
  "Book the appointment.",
  "Have the conversation.",
  "There is rarely a magical day when everything becomes convenient.",
  "Begin inside imperfect conditions.",
  "Waiting for life to calm down can become a lifetime.",
  "Make progress inside the mess.",
  "You do not need perfect circumstances to make a good decision.",
  "Adaptation beats waiting.",
  "Plans should bend before they break.",
  "A changed plan is not automatically a failed plan.",
  "Detours still move you.",
  "Recalculating is part of navigation.",
  "Do not confuse changing direction with giving up.",
  "Persistence means serving the goal, not worshiping the method.",
  "If the strategy fails, change the strategy.",
  "Keep the lesson.",
  "Drop the ego.",
  "Ask what is working.",
  "Ask what is not.",
  "Stop repeating something just because you already invested in it.",
  "Past investment does not justify future waste.",
  "Sunk costs sink more when you keep feeding them.",
  "Know when to quit.",
  "Quitting the wrong thing can save the right thing.",
  "Endings create room.",
  "Not every unfinished project deserves finishing.",
  "Finish what matters.",
  "Release what does not.",
  "Priorities require sacrifice.",
  "Saying yes to everything means quietly saying no to something important.",
  "Every commitment consumes part of your life.",
  "Spend commitments carefully.",
  "Your schedule cannot contain fifteen top priorities.",
  "Important and urgent are not synonyms.",
  "Emergencies love people without boundaries.",
  "Poor planning by others does not automatically create your emergency.",
  "Help when you can without inheriting the chaos.",
  "Do not reward chronic disorganization with unlimited rescue.",
  "People adapt to the boundaries you consistently maintain.",
  "Consistency teaches better than speeches.",
  "Say what you mean the first time.",
  "Calm repetition is more powerful than escalating explanations.",
  "No can be a complete sentence.",
  "A reason is optional, not mandatory.",
  "Overexplaining often sounds like asking permission.",
  "Clear is kind.",
  "Ambiguity feels kinder until the consequences arrive.",
  "Do not make promises just to escape an uncomfortable moment.",
  "Temporary discomfort beats long-term resentment.",
  "Speak truth before resentment edits your tone.",
  "People cannot respect needs you never communicate.",
  "Mind-reading is not a relationship skill.",
  "Do not assume motives when behavior is enough to address.",
  "Talk about what happened, not the villain you imagine behind it.",
  "Facts keep conversations grounded.",
  "Labels make people defend identities instead of solving problems.",
  "Describe the behavior.",
  "Describe the impact.",
  "Ask for the change.",
  "Decide what you will do if nothing changes.",
  "A boundary describes your behavior, not controls theirs.",
  "You cannot enforce a boundary by controlling another adult.",
  "Decide what access your life permits.",
  "Boundaries are doors, not cages.",
  "You can unlock them when trust changes.",
  "You can lock them when behavior changes.",
  "Access should match behavior.",
  "Familiarity does not entitle anyone to unlimited access.",
  "Love is not a lifetime backstage pass.",
  "Family titles do not erase accountability.",
  "Shared blood does not guarantee shared values.",
  "Respect is still required at home.",
  "You teach children boundaries by respecting theirs too.",
  "Adults remember how you made them feel when they were small.",
  "Praise effort intelligently, not blindly.",
  "Let people solve manageable problems.",
  "Competence grows through responsibility.",
  "Protecting someone from every failure can protect them from growth.",
  "Let people experience earned confidence.",
  "Do not do for someone what they need to learn to do themselves.",
  "Guidance works better than control.",
  "Advice is easier to accept when it is invited.",
  "Ask whether someone wants comfort or solutions.",
  "Sometimes people need a witness, not a mechanic.",
  "Listening can be useful without fixing.",
  "Not every sadness is a problem to solve.",
  "Not every silence needs filling.",
  "Sit with people without performing.",
  "Presence can be practical.",
  "Remember names.",
  "Remember small details people tell you.",
  "People notice when you actually listen.",
  "Give credit generously.",
  "Take responsibility quickly.",
  "Praise publicly when appropriate.",
  "Correct privately when possible.",
  "Never humiliate someone to prove authority.",
  "Respect earns more cooperation than intimidation.",
  "Fear creates compliance, not loyalty.",
  "Leadership is what happens when the title is absent.",
  "People copy what leaders tolerate.",
  "Standards mean little when exceptions become normal.",
  "Culture is repeated behavior.",
  "What gets rewarded gets repeated.",
  "Fix systems before blaming people for predictable failures.",
  "If everyone keeps making the same mistake, inspect the process.",
  "Good systems assume humans are human.",
  "Design around reality, not ideal behavior.",
  "Make instructions obvious.",
  "Label things.",
  "Put information where people need it.",
  "Remove unnecessary choices.",
  "Fewer steps usually means fewer errors.",
  "Confusion is feedback.",
  "If everyone asks the same question, answer it in the system.",
  "Documentation saves memory.",
  "Checklists outperform confidence.",
  "Pilots use checklists for a reason.",
  "Routine tasks still deserve verification.",
  "Familiarity breeds skipped steps.",
  "Slow down around things you think you know perfectly.",
  "Expertise can create blind spots.",
  "Ask the newest person what is confusing.",
  "Fresh eyes see invisible assumptions.",
  "Teach people the reason, not only the rule.",
  "Understanding travels farther than obedience.",
  "Train for exceptions, not just the happy path.",
  "Assume something will eventually go wrong.",
  "Have a backup.",
  "Know where the shutoff is.",
  "Know where the exit is.",
  "Know who to call.",
  "Safety rules are written in someone's bad day.",
  "Do not remove safeguards because nothing has gone wrong yet.",
  "Absence of disaster is not proof of good design.",
  "Prevention rarely gets applause.",
  "Maintenance rarely looks heroic.",
  "The best emergencies are the ones prevented.",
  "Check batteries before storms.",
  "Keep gas in the car.",
  "Replace things before total failure when failure matters.",
  "Future-you likes boring preparation.",
  "Health is easiest to appreciate after losing it.",
  "Take care of your teeth.",
  "Wear sunscreen.",
  "Wear the seat belt.",
  "Protect your hearing.",
  "Lift with your legs.",
  "Stretch if your body keeps asking you to.",
  "Pain is information, not always an instruction to push harder.",
  "Rest before your body forces it.",
  "Prevention is usually cheaper than treatment.",
  "Make the appointment you keep postponing.",
  "Ask questions at appointments.",
  "Write symptoms or concerns down beforehand.",
  "You know your daily experience better than a five-minute snapshot does.",
  "Experts deserve respect, not unquestioning obedience.",
  "Get another opinion when something important does not add up.",
  "Do not diagnose yourself from one scary search result.",
  "The internet is excellent at turning headaches into funerals.",
  "Use information to ask better questions, not panic faster.",
  "Your body needs boring basics.",
  "Sleep matters.",
  "Food matters.",
  "Movement matters.",
  "Connection matters.",
  "Sunlight matters.",
  "Routine matters.",
  "None of them need to be perfect to help.",
  "Small improvements compound physically too.",
  "A short walk counts.",
  "One good meal counts.",
  "Going to bed thirty minutes earlier counts.",
  "Drinking water counts.",
  "Progress does not require punishment.",
  "Sustainable beats extreme.",
  "If a plan requires hating your life, it probably will not last.",
  "Build routines you can tolerate repeatedly.",
  "The best workout is one you actually keep doing.",
  "The best diet is one that nourishes you and survives real life.",
  "Your body is not an enemy to defeat.",
  "Your mind works better when your body is supported.",
  "Stress has a physical bill.",
  "Learn what lowers your baseline.",
  "Protect quiet time.",
  "Do not fill every silence with stimulation.",
  "Boredom can restart creativity.",
  "Constant input leaves little room for original thought.",
  "Put the phone down sometimes.",
  "You do not need to know everything happening everywhere.",
  "News without limits can become anxiety disguised as awareness.",
  "Choose what deserves access to your mind.",
  "Attention is your life in tiny pieces.",
  "What you repeatedly look at becomes part of your inner world.",
  "Curate your inputs.",
  "Unfollow things that reliably make you worse.",
  "You do not owe algorithms your nervous system.",
  "Outrage is profitable.",
  "Anger keeps people scrolling.",
  "Not every controversy deserves your opinion.",
  "You can know less about strangers and more about your own life.",
  "Privacy is still valuable.",
  "Do not post every thought while it is still forming.",
  "The internet remembers longer than moods last.",
  "Screenshots survive deleted posts.",
  "Never send anything you could not survive seeing forwarded.",
  "Digital does not mean temporary.",
  "Keep private things private.",
  "Do not confuse visibility with importance.",
  "An audience can distort your priorities.",
  "Popularity is not intimacy.",
  "Followers are not necessarily friends.",
  "Engagement is not affection.",
  "Going viral is not a retirement plan.",
  "Make things you would still like without applause.",
  "Create before consuming.",
  "Do not let other people's work intimidate your unfinished work.",
  "Every polished thing began badly.",
  "Drafts are supposed to be rough.",
  "Editing is where good ideas become useful.",
  "Make something before judging it.",
  "Separate creation from criticism.",
  "You cannot brainstorm and prosecute yourself at the same time.",
  "Quantity often discovers quality.",
  "Ten mediocre ideas may hide one excellent one.",
  "Bad ideas are stepping stones.",
  "Weird ideas deserve a trial before execution.",
  "Originality often begins as something that feels slightly wrong.",
  "Taste develops faster than skill.",
  "Keep going while your ability catches your standards.",
  "Study what you love without cloning it.",
  "Steal principles, not identities.",
  "Constraints can improve creativity.",
  "Unlimited options can paralyze.",
  "Give yourself rules when you feel stuck.",
  "Remove one thing.",
  "Simplify the concept.",
  "Make the main idea obvious.",
  "Decoration cannot rescue confusion.",
  "Style should serve purpose.",
  "Clear beats clever when people need information.",
  "Clever beats boring when attention is the problem.",
  "Know which problem you are solving.",
  "The tool should fit the job.",
  "Expensive gear cannot replace judgment.",
  "Use what you already know before buying another tool.",
  "Learn shortcuts after learning fundamentals.",
  "Automation should remove repetition, not understanding.",
  "Technology multiplies good systems and bad ones.",
  "Fix the process before automating the mess.",
  "Convenience can hide dependency.",
  "Keep some skills manual.",
  "Know how things work before trusting them completely.",
  "Machines fail.",
  "People fail.",
  "Backups exist because both do.",
  "Test important things before the important moment.",
  "Never debut critical technology during the event if you can avoid it.",
  "Familiar equipment is often better than fancy equipment.",
  "Reliability beats novelty under pressure.",
  "Simple setups have fewer ways to fail.",
  "Carry the adapter.",
  "Label the cable.",
  "Tape down the cable.",
  "Charge the battery.",
  "Bring the spare.",
  "Test the microphone.",
  "Check the input.",
  "Check the output.",
  "Assume someone will unplug something.",
  "Photograph complicated setups before taking them apart.",
  "Future-you will appreciate the evidence.",
  "When troubleshooting, change one variable at a time.",
  "Guessing creates new problems.",
  "Start with the simplest explanation.",
  "Check power first.",
  "Check connections second.",
  "Restarting is cliché because it works annoyingly often.",
  "Read the error message.",
  "Search the exact error.",
  "Document the fix.",
  "The second failure should be easier than the first.",
  "Learn from incidents without turning them into blame rituals.",
  "Ask what allowed the mistake.",
  "Build safeguards around predictable human behavior.",
  "Good design makes mistakes harder.",
  "Great design makes recovery easier.",
  "Expect imperfections.",
  "Leave margin.",
  "Do not schedule every minute.",
  "Do not spend every dollar.",
  "Do not use every ounce of energy.",
  "Margin is where resilience lives.",
  "Leave room for traffic.",
  "Leave room for delays.",
  "Leave room for changing your mind.",
  "Leave room for unexpected good things too.",
  "A packed life has nowhere for opportunity to land.",
  "Sometimes less creates more.",
  "More is not automatically better.",
  "Enough is a powerful word.",
  "Know what enough looks like before chasing more.",
  "Otherwise the finish line keeps moving.",
  "Ambition needs a definition of success.",
  "Decide what winning means to you.",
  "Do not inherit someone else's scoreboard.",
  "Prestige is expensive when you do not actually want the prize.",
  "Choose goals for the life they create, not just the moment they achieve.",
  "Ask what the daily life of your dream actually looks like.",
  "You will live the routine more than the milestone.",
  "Build a good ordinary life.",
  "Most of life is ordinary days.",
  "Do not sacrifice every Tuesday for a hypothetical Saturday.",
  "Enjoy things before they become memories.",
  "Take the picture, then look with your eyes.",
  "Tell people you appreciate them while they can hear it.",
  "Give flowers before funerals.",
  "Call people while calling is still possible.",
  "Ask older people questions.",
  "Record the stories.",
  "Write down family recipes.",
  "Memory is less permanent than it feels.",
  "Save the voicemail.",
  "Take the picture you think you will have another chance to take.",
  "Ordinary moments become important without warning.",
  "People rarely know which day will become a memory.",
  "Be present enough to notice.",
  "Your life is happening before you finish organizing it.",
  "Do not delay every joy until after the next accomplishment.",
  "Celebrate small things.",
  "Mark progress.",
  "Make traditions on purpose.",
  "Give yourself things to look forward to.",
  "Fun is not wasted time.",
  "Play is useful for adults too.",
  "Laugh when nothing productive comes from it.",
  "Not everything needs to become a side hustle.",
  "Keep some hobbies financially useless.",
  "Make things because they delight you.",
  "Be bad at something recreationally.",
  "Competence is not required for enjoyment.",
  "Stop grading every part of your life.",
  "Wonder is worth protecting.",
  "Look at the sky.",
  "Notice seasons changing.",
  "Learn the names of things around you.",
  "Curiosity makes ordinary places bigger.",
  "Travel is useful, but attention can make home interesting too.",
  "Do not wait for vacation to notice your life.",
  "Explore your own neighborhood.",
  "Take different routes.",
  "Ask people how things work.",
  "Try food you cannot pronounce confidently.",
  "Learn enough of another language to be polite.",
  "Being a guest carries responsibilities.",
  "Respect places you visit.",
  "Leave places better than you found them.",
  "Clean up after yourself.",
  "Put the cart back.",
  "Hold the door when it makes sense.",
  "Thank service workers.",
  "Tip appropriately.",
  "Do not make someone else's job harder for entertainment.",
  "Character appears in tiny interactions.",
  "Courtesy costs little.",
  "Kindness is not weakness.",
  "Politeness is not submission.",
  "Firmness is not cruelty.",
  "Confidence does not require dominance.",
  "You can be strong without making other people small.",
  "Secure people do not need constant superiority.",
  "Mockery is easy.",
  "Building things is harder.",
  "Be someone who improves rooms.",
  "Bring solutions when you can.",
  "Bring calm when you cannot.",
  "Do not add chaos just because chaos arrived.",
  "Emotional contagion is real.",
  "Your mood enters rooms before your explanation does.",
  "Regulate before leading.",
  "People borrow calm from calm people.",
  "Speak slower when situations get faster.",
  "Lower your voice when everyone else raises theirs.",
  "Clarity beats volume.",
  "Panic makes simple problems complicated.",
  "Handle the next thing.",
  "Then handle the next.",
  "Large crises are often solved through small sequences.",
  "Prioritize what can cause the most harm.",
  "Protect people before property.",
  "Solve safety before convenience.",
  "Fix the leak before discussing paint.",
  "When overwhelmed, reduce the horizon.",
  "What needs doing in the next ten minutes?",
  "One action can restore agency.",
  "You do not need to feel powerful to act usefully.",
  "Control what is actually yours.",
  "Release what is not.",
  "Worry does not become responsibility just because it feels serious.",
  "Anxiety can demand answers reality does not have yet.",
  "Uncertainty is uncomfortable, not automatically dangerous.",
  "Learn to tolerate unanswered questions.",
  "You cannot guarantee outcomes.",
  "You can improve odds.",
  "Prepare without pretending you can control everything.",
  "Accepting uncertainty is not surrender.",
  "Flexibility is strength.",
  "Trees survive storms partly because they bend.",
  "Rigidity breaks under pressure.",
  "Change is easier when identity is not attached to every habit.",
  "You are allowed to become someone your younger self did not predict.",
  "You are allowed to outgrow old dreams.",
  "A goal can be meaningful even if you later replace it.",
  "Past versions of you were working with less information.",
  "Give them some grace.",
  "Give current-you better tools.",
  "Future-you does not require perfection.",
  "Future-you benefits from one useful choice.",
  "Make one.",
  "Then another.",
  "Consistency is accumulated ordinary choices.",
  "Big transformations are usually boring up close.",
  "The dramatic breakthrough often rests on months of quiet work.",
  "Respect repetition.",
  "Respect recovery.",
  "Respect rest.",
  "Respect limits.",
  "Respect time.",
  "Respect consequences.",
  "Respect yourself enough to be honest with yourself.",
  "Do not lie to yourself just because the truth is inconvenient.",
  "Self-deception charges interest.",
  "Name the problem accurately.",
  "You cannot solve what you keep renaming.",
  "If you messed up, say you messed up.",
  "Explanations are useful; excuses are endless.",
  "Responsibility gives you leverage.",
  "Blame gives you a target but not always a solution.",
  "Focus on what you can change next.",
  "Accountability is not humiliation.",
  "Own the decision without hating the person who made it.",
  "You can become wiser without despising who you were.",
  "Wisdom often looks like avoiding problems you once thought you had to conquer.",
  "Maturity is knowing which fires do not need your gasoline.",
  "Sometimes growth is losing the urge to prove yourself.",
  "Sometimes success is leaving earlier.",
  "Sometimes courage is staying.",
  "Sometimes strength is asking for help.",
  "Sometimes kindness is saying no.",
  "Sometimes loyalty is telling the truth.",
  "Sometimes love is giving space.",
  "Sometimes forgiveness is permanent distance without hatred.",
  "Sometimes confidence is admitting uncertainty.",
  "Sometimes leadership is listening.",
  "Sometimes progress is resting.",
  "Sometimes discipline is stopping.",
  "Sometimes winning is refusing to play.",
  "Sometimes the answer is simpler than your pride wants it to be.",
  "Sometimes the lesson costs more because you refused the cheaper version.",
  "Learn while tuition is low.",
  "Pay attention to small warnings.",
  "Problems whisper before they shout.",
  "Cracks are easier to fix than collapses.",
  "Conversations are easier before resentment.",
  "Bills are easier before penalties.",
  "Maintenance is easier before failure.",
  "Apologies are easier before distance.",
  "Health is easier before crisis.",
  "Boundaries are easier before burnout.",
  "Truth is easier before lies multiply.",
  "Start early when you can.",
  "Stop early when you should.",
  "Stay curious longer than you stay angry.",
  "Ask what this is trying to teach you.",
  "Keep the lesson and release the punishment.",
  "Become difficult to manipulate by knowing yourself.",
  "Become difficult to discourage by knowing why you started.",
  "Become difficult to fool by watching actions.",
  "Become difficult to overwhelm by knowing what matters next.",
  "Become difficult to control by being willing to walk away.",
  "Become easy to trust by doing what you say.",
  "Become easy to work with by communicating clearly.",
  "Become easy to love by letting yourself be known.",
  "Become easier on yourself without lowering your standards.",
  "Life improves when ego stops driving every decision.",
  "Wisdom is often knowing what not to respond to.",
  "Peace is often deciding what no longer gets access to you.",
  "Freedom is often realizing you can choose differently.",
  "Your life changes through decisions nobody else can make for you.",
  "Keep what makes you wiser.",
  "Leave what makes you smaller.",
  "When you know better, make the next choice better.",
];
